### ISSUE TITLE
header of the countries table switches

### ISSUE THREAD

**Issue by aaronkaplan** [cybergreen-net/stats-new#1]
When scrolling down the table of countries in the new stats page, the header line (risk names) moves to the left.
Please inspect. 

How to repeat: 
  * scroll down
  * observe header of the table.
  * Use Google Chrome

**Comment by Fak3** [comment]
Please reopen this. It works locally, but still fails in the production. Something to do with jquery\plugin load order.

**Comment by aaronkaplan** [comment]
reopened but... actually in the heroku version, it works for me now...

**Comment by Fak3** [comment]
It surely does not work for me on heroku. 
```
jquery.floatThead.min.js:3 - Uncaught ReferenceError: jQuery is not defined
table.js:45 - Uncaught TypeError: $(...).floatThead is not a function
```

**Comment by aaronkaplan** [comment]
---
Mobile

> On 01.10.2016, at 12:24, Evstifeev Roman <notifications@github.com> wrote:
> 
> It surely does not work for me on heroku.
> 
> jquery.floatThead.min.js:3 - Uncaught ReferenceError: jQuery is not defined
> table.js:45 - Uncaught TypeError: $(...).floatThead is not a function

Interesting. Anyway, I guess it should work for all of us. So... This seems indeed to be an issue -> still open.

**Comment by aaronkaplan** [comment]
I meant please re-open. 


---
Mobile

**Comment by zelima** [comment]
@aaronkaplan @Fak3 I may not have deployed changes to heroku before the time you tested it.
Please retest and share results. Works fine for me too

**Comment by Fak3** [comment]
Oh, it works sometimes (!) Refreshing many times leads to different results.

**Comment by aaronkaplan** [comment]
> On 03 Oct 2016, at 14:00, Evstifeev Roman <notifications@github.com> wrote:
> 
> Oh, it works sometimes (!) Refreshing many times leads to different results.
> 

funny. It always works for me when I refresh.
Which browser do you use?

**Comment by Fak3** [comment]
I tried firefox, chrome and chromium. All the same.

**Comment by Fak3** [comment]
I am using ctrl-shift-R to refresh ignoring cahes

**Comment by Fak3** [comment]
Just tried from another pc with the same results.

**Comment by zelima** [comment]
@Fak3 Ok, can you fix that?

**Comment by Fak3** [comment]
I can try. I don't yet know how to force jquery to load before the plugin.

**Comment by zelima** [comment]
Ok, lets try. 
But give low priority, for now

**Comment by aaronkaplan** [comment]
> On 04 Oct 2016, at 14:29, Irakli Mchedlishvili <notifications@github.com> wrote:
> 
> Ok, lets try.
> But give low priority, for now

Guys do you think this could be related to heroku?

**Comment by Fak3** [comment]
No, I can reproduce it with local server.
