### ISSUE TITLE
ASN Tree map: hover provides info on ASN

### ISSUE THREAD

**Issue by rufuspollock** [cybergreen-net/stats-new#101]
tree map: allow for hovering over a tree map item and get the AS name (and maybe the abuse contact) . Possibly also link to stat.ripe.net (such as: https://stat.ripe.net/AS35492)

**Comment by chorsley** [comment]
This data is available at https://github.com/cybergreen-net/asname-historical.

**Comment by zelima** [comment]
INVALID we do not use treemap any more and data is available here https://github.com/cybergreen-net/refdata-asn
