### ISSUE TITLE
Front page map is very slow to load

### ISSUE THREAD

**Issue by rgrp** [cybergreen-net/stats-new#104]
[ 3 ]
Reason is simple: we are now loading all data for all periods before we render the map (7Mb+).

Solution: we need to change to load data on demand for particular time periods (and risks).

**Comment by aaronkaplan** [comment]
sounds good.

**Comment by zelima** [comment]
@rgrp As a solution I was thinking to pass the "dynamic url" to JS code E.g: 
http://stats.cybergreen.net/api/v1/count_by_country?start=2016-09-19&end=2016-10-19&risk=openntp&limit=500
That would return results only for that exact date and risk and not load All the data

**Comment by rgrp** [comment]
@zelima right now simplest solution given how frontend works i would suggest we do:

http://stats.cybergreen.net/api/v1/count_by_country?start=START&end=END

With START and END computed in backend and passed to frontend as we discussed.

**Comment by zelima** [comment]
Fixed - Currently data for only last three dates are loaded, so map is reasonably faster than it was.
Closing for now.
