### ISSUE TITLE
[super] UX changes beta3

### ISSUE THREAD

**Issue by zelima** [cybergreen-net/stats-new#105]
- [ ] Time series graphs added on `/country`, `/country/{id}`, `/risk/{id}`, `/country/{country_id}/{risk_id}`

  - `/country`: Showing line graph of count (_for total country and risk_) over time
    - other option for this page would be a sparkle lines for each country [see slide](https://docs.google.com/presentation/d/14-tJ3Ca0qstmgwLENQh5jflChB4MxZoUkA96fFoqGbU/edit#slide=id.g19d3b49a57_3_16)
  - `/country/{id}`: Showing 4 line graph of count (_for given country and 4 different risk_) over time
  - `/risk/{id}`: Showing line graph of count (_for given risk and total country_) over time
  - `/country/{country_id}/{risk_id}`: Showing line graph of count (_for given country and risk_) over time
  - Graphs By default are showing weekly data 
- [ ] ability to switch between different time granularities - week, month, quarter, year
  - Buttons above graphs for switch
    - does this mean we need to preload all needed data?
- [ ] Table changes
  - get rid of scores and color-coding (for now)
  - include amplified count as well as regular count
  - include total risk and total country in tables

See [slide deck](https://docs.google.com/presentation/d/14-tJ3Ca0qstmgwLENQh5jflChB4MxZoUkA96fFoqGbU/edit#slide=id.g13c7436e56_1_15) to see visual differences

**Comment by rufuspollock** [comment]
INVALID. CLOSING as FIXED / DUPLICATE / INVALID. There's a variety of things in here - some we will do, some we won't etc. Better right now just to close and we have sub issues for items we are doing.
