### ISSUE TITLE
Fix html title tag to be useful for each page

### ISSUE THREAD

**Issue by rufuspollock** [cybergreen-net/stats-new#106]
Currently each page has the same not useful title:

` | Global by`

This is not super urgent, but definitely useful to do.

**Comment by zelima** [comment]
FIXED.

**Comment by rufuspollock** [comment]
@zelima could you put a small note of what the title's now look like?

**Comment by zelima** [comment]
Page titles are showing `{page-name} | Global {site-name} by {author}` Eg:
- `Home | Global Cybergreen Statistics by Cybergreen`
- `Countries | Global Cybergreen Statistics by Cybergreen`
- `UK | Global Cybergreen Statistics by Cybergreen`
etc...

**Comment by rufuspollock** [comment]
@zelima can we remove the `by {author}` stuff as it will say nothing useful.

{page-name} should include section e.g. UK Country page should be:

```
UK - Country Statistics | ...
```

Also can we set default site name to:

```
Cyber Health Statistics - CyberGreen
```

This will be better for SEO.

**Comment by zelima** [comment]
@rufuspollock can we list out for each of them what there should be before `| Cyber Health Statistics - CyberGreen`?
- [home page](http://cybergreen-staging.herokuapp.com/) - `Home`
- [country page](http://cybergreen-staging.herokuapp.com/country/) - `Country Statistics`
- [country-id](http://cybergreen-staging.herokuapp.com/country/united-kingdom/) - `UK - Country statistics`
- [country/asn-id page](http://cybergreen-staging.herokuapp.com/country/united-kingdom/asn/1257/)- `1257 - AS statistics`
- [risk page](http://cybergreen-staging.herokuapp.com/risk/) - `Risk Statistics`
- [risk-id page](http://cybergreen-staging.herokuapp.com/risk/openntp/) - `Open NTP Risk Statistics`
- [country-di/risk-id page](http://cybergreen-staging.herokuapp.com/country/afghanistan/openntp/) - `UK Open NTP Country statistics`
- [asn page](http://cybergreen-staging.herokuapp.com/asn/) - `ASN statistics`
- [Download & API](http://cybergreen-staging.herokuapp.com/download/) - `Download & API`
- any other page if I missed

**Comment by rufuspollock** [comment]
@zelima i've updated.

**Comment by zelima** [comment]
Moving to next milestone. Was with low priority, did not fit in time

**Comment by zelima** [comment]
FIXED page titles named as defined above
