### ISSUE TITLE
Evaluate DataBrewery cubes

### ISSUE THREAD

**Issue by rufuspollock** [cybergreen-net/stats-new#107]
http://cubes.databrewery.org/

Could use this for running our API access etc.

Seems like the server provided by cubes will deliver a "slicer" API out of the box if properly configured.

Using cubes would imply a switch to flask (and python) from express (and node) but not sure that is a big deal esp with zappa deployment.

NOTE: we would not make such a switch for beta-3 but afterwards.

**Comment by rufuspollock** [comment]
@zelima worked on this and needs to write up. Needs to check a bit what he did.

**Comment by zelima** [comment]
@rufuspollock_ I've gone through their docs a bit and tutorials. Worked with sample data they've provided in tutorials. Even connected to our RDS dev database and tried some slicing and dicing there... 
Seems very easy and useful tool!

**Comment by zelima** [comment]
Closing for now

**Comment by rufuspollock** [comment]
@zelima could you write up in a bit more detail what you found. e.g. do you have a gist of your code for setting this up and connecting it to a DB? Could you link to key API documentation etc.

**Comment by zelima** [comment]
Documentation and Tutorial can be found here https://cubes.readthedocs.io/en/latest/tutorial.html
Here is the gist for simple drilldowns https://gist.github.com/zelima/5d12b529959ca0bf07366df270324259

There are two ways to connect to database:
- Create `slicer.ini` file and keep db information there Eg:

```
[store]
type: sql
url: postgresql://user:password@server:5432/db
```
- Or define inside python script (see gist for example)

Also we have to predefine dimensions and aggregation functions in `model.json` (see gist for example)
`model.json` could also be defined in `slicer.ini`
