### ISSUE TITLE
Stats changes to UI

### ISSUE THREAD

**Issue by zelima** [cybergreen-net/stats-new#114]
* [x] Remove score / refactor score
* [x] Show count / amplified count on country list
* [x] Show count / amplified count on country/{id}
* [x] Show count / amplified count on risk/{id}

**Comment by zelima** [comment]
**Country list page**
![image](https://cloud.githubusercontent.com/assets/15143785/21193582/32e369b2-c246-11e6-948e-24b15a9b46e1.png)

**Country/{id}** page
![image](https://cloud.githubusercontent.com/assets/15143785/21193637/6448422a-c246-11e6-9b7b-9744ec260a04.png)

**Risk/{id}** page
![image](https://cloud.githubusercontent.com/assets/15143785/21193709/a33649e6-c246-11e6-954f-2b554cfa57d0.png)

**Comment by zelima** [comment]
@rufuspollock could you please review this

**Comment by rufuspollock** [comment]
FIXED. Remaining item to add "total amplified count" to /country/ table #119.
