### ISSUE TITLE
/asn/{id} page graphs show values on hover

### ISSUE THREAD

**Issue by rgrp** [cybergreen-net/stats-new#13]
Currently no hover over just line graph.

Probably some other minor prettifying we could do.

**Comment by aaronkaplan** [comment]
@rgrpl let's actually do so Post Sept-30 (wishlist). I'd like to have the same and actually the same request in #34 . Keeping this closed since it's a dup of #34

**Comment by zelima** [comment]
@aaronkaplan Graph is showing counts on hover eg: http://cybergreen-stats.herokuapp.com/country/colombia/asn/10299/
Can we close this one and open new for improvements?

**Comment by aaronkaplan** [comment]
@zelima Thanks cool!
Minor improvement: at least in Google Chrome the line is quite hard to hit with the mouse. So, some distance check (e.g. distance (mouse(x,y), line) < 4 pixels) would make a big difference in useabilitity.

But, this can be done later.
I'd rather keep this issue open. It's already assigned to the post-spet-30 milestone, so we are fine.
Not now.
thanks!
