### ISSUE TITLE
bug: new columns in the country/ table can't be sorted

### ISSUE THREAD

**Issue by aaronkaplan** [cybergreen-net/stats-new#130]
How to repeat?

* click on the column header ( in the  /country/ page ) "OpenNTP" -> works. Click on the next column header -> works
* click on "OpenSSD AF" -> does not work anymore.
* Same for all the other remaining column headers

* Column headers are too large (the text wraps around).

**Comment by aaronkaplan** [comment]
any news on this?

**Comment by zelima** [comment]
FIXED in https://github.com/cybergreen-net/stats-new/commit/deb58d8fdb8721a430c35db54b9fea5eb24fcbeb
See https://cybergreen-staging.herokuapp.com/country
