### ISSUE TITLE
Change "counts" to "units" for Global DDOS potential graph on country page 

### ISSUE THREAD

**Issue by zelima** [cybergreen-net/stats-new#131]
Currently graph is showing pure count sums with amplification factor.
We need this to be changed Into units
@aaronkaplan says:
> if we assume an average of 1 MBit/sec per device which can contribute to a DDOS, then the units will be TBit/sec
4 10^9 MBit/sec = 4 10^6 GBit / sec = 4* 10^3 TBit/sec  

So we need to divide existing number by 10^6 and label Y-axes as "GBit/sec"

**Comment by aaronkaplan** [comment]
agreed, and we need some footnote /small text below about the assumption that we have: "This graph assumes an average 1 mbit/sec Internet connection for every IP address."

**Comment by zelima** [comment]
Moving to next milestone. UI changes will be done after refactoring to React

**Comment by zelima** [comment]
FIXED
Time series line graphs changed with stacked bar charts. Moved on Home page.
Y axis labeled as `GBit/sec`. Has little description below
