### ISSUE TITLE
Render vega line graphs using React

### ISSUE THREAD

**Issue by zelima** [cybergreen-net/stats-new#135]
- [x] Create component responsible for rendering linechart on main page. 
- [x] Insert line chart with simplest vega-spec and data
- [ ] Refactor component to render the actual data 
- [ ] Refactor vega-spec with needed specifications (hover etc...)

**Comment by rufuspollock** [comment]
@zelima can you start putting more description in these issues - what are the steps involved.

@zelima also i think we should consider what we use here - is it vega?

**Comment by zelima** [comment]
@rufuspollock Updated. 
I follow examples and suggestions provided in this blogpost https://medium.com/@pbesh/react-and-vega-an-alternative-visualization-example-cd76e07dc1cd#.31xk3zx08

And yes, still using vega for now

**Comment by zelima** [comment]
WONTFIX. we probably will switch to plotly
