### ISSUE TITLE
timeout when using the API

### ISSUE THREAD

**Issue by aaronkaplan** [cybergreen-net/stats-new#137]
Hi,

trying to use the API results in a timeout on Heroku.

Example:
https://stats.cybergreen.net/api/v1/count?asn=3333 -> timeout.

Please note: this is a regression. It should not happen again and again and again.
I'd like to have this fixed for ever please.
I assume you simply _always_ have to create the proper index in the postgresql RDS DB.

![image](https://cloud.githubusercontent.com/assets/750019/21998116/4080f13c-dc33-11e6-8668-803afcfa7550.png)

Same thing for the staging site.
please fix.

**Comment by zelima** [comment]
@aaronkaplan This make me very confused. When running  `EXPLAIN same exact query` I'm getting this result:
```
QUERY PLAN                                                
---------------------------------------------------------------------------------------------------------
 Limit  (cost=0.56..205001.41 rows=20 width=79)
   ->  Subquery Scan on foo  (cost=0.56..307501.83 rows=30 width=79)
         ->  GroupAggregate  (cost=0.56..307501.53 rows=30 width=27)
               Group Key: fact_count.date, fact_count.country, fact_count.risk, fact_count.asn
               ->  Index Scan using idx_all_desc on fact_count  (cost=0.56..307497.30 rows=297 width=27)
                     Index Cond: (asn = 3333)
```
Indexes are set up properly. It should take **56 milliseconds** to return result.
Anyway I made some changes to optimize query and it should work for now (for staging site).

My overall comment here would be that  there might be some other issues - in general API needs to be refactored as we have switched to new DW structure. E.g: You might notice that staging website still returns only "count" instead of returning count with amplification factor.

This needs to be properly planned and implemented so that we don't run in the issues like this over and over again. As our priority for now is UX changes according to new user stories this might take some time to be complete.

**Comment by zelima** [comment]
FIXED closing for now

**Comment by aaronkaplan** [comment]
Okay. Understood. Thx for the explanation. 
I thought it was the same Index Problem again 

Nevertheless - the API should not time out on the beta-2 
Stats site: stats.cybergreen.net. 

After all, we do not have that much data once it is aggregated. 

At least I want to be able to show the old stats.cybergreen.net site to new users without timeouts. 

---
Mobile

**Comment by aaronkaplan** [comment]
Sorry this is not closed. 

---
Mobile

**Comment by zelima** [comment]
@aaronkaplan stats.cybergreen.net should be working as well for now.

**Comment by aaronkaplan** [comment]
> On 17 Jan 2017, at 11:16, Irakli Mchedlishvili <notifications@github.com> wrote:
> 
> @aaronkaplan stats.cybergreen.net should be working as well for now.

Tested with https://stats.cybergreen.net/api/v1/count?asn=3333.
It does (with this URL). Thanks!!

What was the issue with the main stats site?

**Comment by zelima** [comment]
Well to be honest this is a bit unclear for me. But This are the changes I made:
- previously Query looked like this (example):
`SELECT * FROM count WHERE  asn::text = '3333' ` 
- Changed it to:
`SELECT * FROM count WHERE  asn::number = 3333`

Here are full changes https://github.com/cybergreen-net/stats-new/commit/b8fe3c033d4cd8aa823fd734df36875d0c5fe4b0

I say unclear cause query plan for both of them were same.

**Comment by aaronkaplan** [comment]
> On 17 Jan 2017, at 12:17, Irakli Mchedlishvili <notifications@github.com> wrote:
> 
> Well to be honest this is a bit unclear for me. But This are the changes I made:
> 
> 	• previously Query looked like this (example):
> SELECT * FROM count WHERE asn::text = '3333'
> 	• Changed it to:
> SELECT * FROM count WHERE asn::number = 3333
> Here are full changes b8fe3c0

Well it does seem that the index was on the AS *number* and that it could actually use the index now...

that's at least what my postgresql know-how would suggest.

> 
> I say unclear cause query plan for both of them were same.
> 
Hm, maybe not internally...
