### ISSUE TITLE
API count by country v2

### ISSUE THREAD

**Issue by zelima** [cybergreen-net/stats-new#139]
### Will be used by Global Potential DDOS graph 

* Endpoint: `/api/v1/count_by_country`
* What we need to be retrived (for graph): date, risk, amplified count
* Example query: `/api/v1/count_by_country?country=global&risk=ddos&granularity=week&limit=500&page=1`
* Expected result: 
```
{
    total: xxx
    result:[
        {"risk":"null","country":"null","date":"2017-01-01","count":"114842","count_amplified":"214842"}
    ]
}
```
Possible query strings:
* `?granularity`  defaults to week
    * options: week, month, quarter, annual
* `?limit` defaults to 20
    * options: Integer between 1 - 500
* `?page` defaults to 1
    * options: Integer
* `?risk`
    * options: 100 (ddos),1,2,4,5,6,
* `?country`
    * options: ISO 3166-1 alpha-2 code fo country, T (total)
* `?start` and `?end`
    * optons: ISO 8601 formated date

>>[Irakli]: null's here represents "global" country and risk. Meaning do not excluding mirai (or any other) at least for now.
>>[Irakli]: What about returning risk names? country names? instead of returning just their ID. Eg:  openntp for 1, or united-kingdom for GB
>>Generaly, do we have user stories for API? 

* Example SQL query: 
    ```
    SELECT risk, country, date, count, count_amplified, period_type
    FROM table_by_week
    WHERE 
        date IS NOT NULL 
        AND risk=$risk  //null
        AND country=$country //null
        AND period_type=$period_type //week
    ORDER BY date DESC
    LIMIT $limit //500
    OFFSET $page //1
    ```

**Comment by aaronkaplan** [comment]
> On 17 Jan 2017, at 16:22, Irakli Mchedlishvili <notifications@github.com> wrote:
> 
> Will be used by Global Potential DDOS graphs
> 
> 	• Endpoint: /api/v1/count_by_country
> 	• What we need to be retrived (for graph): date, risk, amplified count
> 	• Example query: /api/v1/count_by_country?country=global&risk=ddos&granularity=week&limit=500&page=1
> 	• Expected result:
> {
>     total: xxx
>     result:[
>         {"risk":"null","country":"null","date":"2017-01-01","count":"114842","count_aplified":"214842","period_type":"week"}
>     ]

typos: "count_aMplified" (m was missing)

> }
> 
> [Irakli]: null's here represents "global" country and risk. Meaning do not excluding mirai (or any other) at least for now.
> [Irakli]: What about returning risk names? country names? instead of returning just their ID. Eg: openntp for 1, or united-kingdom for UK
> Generaly, do we have user stories for API?

Yes, please risk names
Otherwise, it's hard for consumers of the API

**Comment by zelima** [comment]
FIXED handles with global risk (ddos) and global county "T". Handles with different time granularity. Risk name and country name still missing for now. Will be fixed with after discussion is complete here https://github.com/cybergreen-net/stats-new/issues/121
