### ISSUE TITLE
Rank API (per risk)

### ISSUE THREAD

**Issue by rufuspollock** [cybergreen-net/stats-new#155]
```
/api/rankings?risk=xyz&date=xxx&granularity=abc&country=YYY
```

required options:
- risk 
- date (latest period)
- granularity (defaults to month)

### Proposed result

list of all countries within given time period and granularity for given risk Eg:
```
[
  {
   country: YY,
   rank: 1
  },
  {
   country: XX,
   rank: 2
  }
]
```

**Comment by zelima** [comment]
FIXED https://cybergreen-staging.herokuapp.com/api/v1/rankings?risk=1
