### ISSUE TITLE
Swagger-ize the API

### ISSUE THREAD

**Issue by rufuspollock** [cybergreen-net/stats-new#156]
* [x] Document current API with swagger stuff
* [x] Add it https://github.com/swagger-api/swagger-node
* [x] Add swagger-ui repo https://github.com/swagger-api/swagger-ui as `api-docs/`

Finally, download the Swagger UI repo, add the “dist” folder from the downloaded repo to the “public” folder in the project directory, and then rename the directory to “api-docs”.

Now within index.html inside the “api-docs” directory just update this line:

```
url = "http://petstore.swagger.io/v2/swagger.json";
```

To our API URL: `/api/swagger.json` (or equivalent)

**Comment by zelima** [comment]
FIXED API is swagger-ized. see results  https://cybergreen-staging.herokuapp.com/api-docs/#/default

**Comment by zelima** [comment]
All Descriptions for list of API operations say the same thing: `Returns aggregated results drilled down to country level`

**Comment by zelima** [comment]
FIXED in https://github.com/cybergreen-net/stats-new/commit/49f9c972f2da6f2c6b1275da515bff26ec47a2fc

**Comment by anuveyatsu** [comment]
@zelima done
