### ISSUE TITLE
Spreadsheet of info which is loaded from config

### ISSUE THREAD

**Issue by GregoryRhysEvans** [cybergreen-net/stats-new#16]
A google spreadsheet containing info, which can be easily edited by non-technical users.

This would contain, for example, the descriptive text for pages.

The config.js should be configured to load this spreadsheet

Why? It would allow non-technical users to update content on the site quickly and easily (without having to edit nunjucks templates and run node.js apps or use up dev time on content changes!)

**Comment by aaronkaplan** [comment]
What info do you mean? and why? In general I am fine with assuming people need to edit CSV files (for now at least).

**Comment by zelima** [comment]
@aaronkaplan We would use this for description parts of pages. Right now they are hardcoded into the html files. Eg: info on home page, `/risk` and `/country` pages etc...

**Comment by aaronkaplan** [comment]
yes. But AFAIK we have this info already in a CSV. Right?

**Comment by zelima** [comment]
Did not know about that, which CSV contains that info?

**Comment by zelima** [comment]
@aaronkaplan thing this needs to be cleared up. By info we mean "descriptions" for example:
```
The following table lists countries scored by how well they are doing based on four different criteria:
- number of open recursive DNS devices (opendns)
- number of open NTP devices (openntp)

etc...
```
from country page http://cybergreen-stats.herokuapp.com/country/

**Comment by aaronkaplan** [comment]
I am still not sure how this should look. Could you make an example CSV and show me how and where it is mapped in and I can fill it up?

**Comment by zelima** [comment]
@aaronkaplan I thinking of something like this: https://gist.github.com/zelima/1371385ec40d7d665cc04d6219f94e97#file-descriptions-csv

**Comment by rgrp** [comment]
@aaronkaplan does this now make sense to you? 

About the Why of this:

It would allow non-technical users to update content on the site quickly and easily (without having to edit nunjucks templates and run node.js apps or use up dev time on content changes!)

**Comment by zelima** [comment]
WONTFIX front end refactored so that does not need much text to be displayed any more. 
Only page with descriptive text would probably be the `/donwload&API` page ad will be hard coded in HTML. 
No need of this any more.
