### ISSUE TITLE
Refactoring the API based on frontend needs

### ISSUE THREAD

**Issue by zelima** [cybergreen-net/stats-new#166]
Data that API response should include when requested for graphs:

### DDOS graphs:
- list of entries with `count_amplified` and `date` for each date with given granularity, keys for given risk

### country performance 
- list of entries with `count_normalized` and `date` keys for each date with given granularity, for given risk and country

### country source of infection
- list of entries with `count` and `date` keys for 9 "worst" AS, for each date with given granularity, given risk and country

### AS performance 
- list of entries with `count` and `date` keys for each date with given granularity, for given risk and country and AS

**Comment by rufuspollock** [comment]
@zelima i'm moving to backlog until we're clear what is actually involved here. Can you clarify what you think is involved.

**Comment by rufuspollock** [comment]
INVALID. This issue has no content.
