### ISSUE TITLE
ASN -> AS in the UI

### ISSUE THREAD

**Issue by rufuspollock** [cybergreen-net/stats-new#167]
Proposal: use `AS` rather than `ASN` in the UI e.g.

"AS 1543" rather than "ASN 1543" in titles of AS page
`/as/` in the URL rather than `/asn/`

**Why?** AS = Autonomous System the (object) whilst ASN is the number (the name of the AS). Currently pages have h1 titles like “ASN 1432” and urls like `/asn/1543` but the actual object is AS not ASN. Having "ASN" is like having "Country Name United Kingdom" rather than "Country United Kingdom".

@aaronkaplan any thoughts here?

**Comment by aaronkaplan** [comment]
Yes, I have some thoughts. So... unfortunately it is never 100% consistent in differente DBs.
The most relevant DB for this (for us) is the RIPE DB. 

There, the nomenclature is not 100% consistent as well.


So, from a domain specific knowledge point I would communicate something about AS**N** 1901, but if I want to talk about the AS, I would talk about "EUNETAT-AS" (that's the AS name).

But let's have a look how it is in the RIPE DB:

```
% whois -r AS1901
(...)
aut-num:        AS1901
as-name:        EUNETAT-AS
```

This would support your theory.

But... to be honest, my domain expert feeling tells me I would rather like to talk about AS**N**s when I talk about numbers and AS-es when I talk about their names.

So, from my perspective, let's keep it as it is for the API, but yes, let's have it changed to "AS foobar" whenever we talk about the name.

@rufuspollock do you need a mapping (global mapping) of AS name to ASN?

**Comment by zelima** [comment]
@rufuspollock @aaronkaplan What is the final decision here? Are we switching to **AS** or not?

**Comment by rufuspollock** [comment]
@zelima we will use AS. In terms of URLs i think we change as well but will need a redirect for old urls if possible.

**Comment by aaronkaplan** [comment]
ACtually I believe I answered to @rufuspollock that whenever there is a *number* we'll call it "ASN".
When we talk about the name , it's "AS".
Why?
Because that's the way it is used in the networking world.

**Comment by zelima** [comment]
I did some changes to UI. Eg: removed "N" from headings of bra charts on country page https://cybergreen-staging.herokuapp.com/country/united-kingdom 
Also some minor changes to `/asn/` page
Did not touch any of URLs

closing as FIXED
