### ISSUE TITLE
Feedback on country page from Aaron 17 Feb 2017

### ISSUE THREAD

**Issue by rufuspollock** [cybergreen-net/stats-new#168]
> So, I went through the current staging site (https://cybergreen-staging.herokuapp.com) and I must say I am pretty impressed with the implementation of our comparative graphs (based on the discussions we had with Rufus , Silvi).
>
> However, there are a couple of things that I noticed, which must not be forgotten:
> ( I will take https://cybergreen-staging.herokuapp.com/country/united-states/ as an example here)
>
> 1. the graphs seem to be wrong. Or at least not understandable.
>   Example: OpenSSDP - compare global and the US. Surely the "global graph" must never be lower than the US graph. After all "global" is the global sum of all countries. Right?

Agreed this is an issue and was discussed at length with Yurie.

Issue is how to present the data to convey the basis point about relative performance.

Ongoing discussion here: https://github.com/cybergreen-net/cg-graphs/issues/22

> 2. there is a deviation from the metric which the stats group defined. In these graphs you have a "normalised count" . But what is this normalised count? I believe there is some invention hidden here but not explained. If so, it must be explained and "OK"ed by the stats group.

See https://github.com/cybergreen-net/cg-graphs/issues/22 again.

Basic answer: normalized here = set XXX date (1 Jan 2017 atm) to 100 for this series (so everything is around that ref value.

Reason: we need comparable numbers for the graph (o/w most countries are dwarfed by global counts). Discussed more in https://github.com/cybergreen-net/cg-graphs/issues/22

> 3. Size of the graphs. If you have many small graphs on the page, you leave a lot of unused white screen estate on the page.
> Let's use it. Or at least let;s have silvie still look over it, how it should be arranged.

There will be whole other set of graphs on the RHS -- see the mockups for the country page :-)
> 4. new "risk" "DDOS". Actually this is a synthetic risk. We should clearly mark synthetic risks (i.e. combined risks based on a combination of metrics) as such and separate it from the risks calculated from our raw data.

You are quite right this is synthetic. How much does it matter for users to know synthetic vs synthetic vs just having a description of the risk.

> 5. labels. Try adding multiple countries with the drop down boxes. The labels will overlap the actual graph. (example: open NTP - US, try adding multiple countries).

Another item discussed with Yurie. There is no easy way to fix this. If we remove labels you don't know which country is which. Any suggestions welcome!

![image](https://cloud.githubusercontent.com/assets/180658/23060526/1023fb46-f539-11e6-8e15-75fcad920198.png)

**Comment by chorsley** [comment]
One suggestion I wanted to sneak in (please feel free to move to a more appropriate issue).

I'd like to suggest fixing each y-axis to start from zero. I assume the y-axis limits currently get chosen based on the range of data values for each series, which may differ significantly from graph to graph on one page. It would make for both easier comparison between graphs, and to not visually exaggerate increases or decreases in a generally flat series of data points by "zooming in" (as in the US open NTP graph above).

**Comment by rufuspollock** [comment]
@chorsley good point and we'll see if we can look at that. The challenge can be that 0 can be a long way away from the data and result in massive flattening of the time series visually ...

**Comment by zelima** [comment]
@rufuspollock one option re labels may be to have backgrounds of selectors (drop-downs) same color as lines. 
@anuveyatsu what do you think? Is it something complicated?

**Comment by anuveyatsu** [comment]
@zelima it might become complicated, because we need to implement it separate from Plotly, but I personally think it would NOT look great if we have different backgrounds for each Dropdown.

**Comment by anuveyatsu** [comment]
I think we could remove legends as on hover a user can see all necessary information.

**Comment by rufuspollock** [comment]
INVALID. I think key items are in https://github.com/cybergreen-net/cg-graphs/issues/22. If other specific issues arising here let's create specific issues.
