### ISSUE TITLE
RDS performance is slow

### ISSUE THREAD

**Issue by zelima** [cybergreen-net/stats-new#170]
Previously we were using the smallest possible DB Instance Class for AWS RDS - `db.t2.micro` 
![image](https://cloud.githubusercontent.com/assets/15143785/23096205/cad59a9c-f630-11e6-9dc3-5136d74436af.png)

This was resulting in **very** slow queries used for API calls 

Currently DB instance class is upgraded to - `db.m4.xlarge` 
![image](https://cloud.githubusercontent.com/assets/15143785/23096222/409e60ec-f631-11e6-8c24-e6af3477ecf8.png)

This is enough for getting results under 5 second For any API call, While previous one was resulting `internal server error` cause of time outs

---

We may need to downgrade till `db.m4.large` (with 8GB memory) as it is twice as cheaper and see the results.

**Comment by aaronkaplan** [comment]
I don't understand why for aggregated data you need a large instance.
The aggregated data is not that big.

Or is the RDS system also used for non-aggregated data?

**Comment by zelima** [comment]
@aaronkaplan No RDS is not used for non-aggregated data, we use Redshift for that. **Memory (GB)** is not actual storage of instance, but RAM memory.

> **Memory (GB)** – Specifies the RAM memory, in gigabytes, allocated to the DB instance. 

More info is available here http://docs.aws.amazon.com/AmazonRDS/latest/UserGuide/Concepts.DBInstanceClass.html#Concepts.DBInstanceClass.Summary

**Comment by aaronkaplan** [comment]
So if I read the comment above correctly, we are using RDS only for aggregated data ("not used for non-aggregated..."). Concerning Memory (= RAM): yes, I understood that.
But nevertheless... if we use RDS only for aggregated data... then we do not need that much RAM. The aggregated data is generally small. Right?

@rufuspollock any comments on the sizing?

**Comment by zelima** [comment]
@aaronkaplan Yes RDS only for aggregated.

Well our main fact table has ~14,000,000 rows for now and definitely  not enough `.615gb` (the one we used to have). Agree that 16 GB may be too much. 
We will try and downgrade to one down some time next week and see the results

**Comment by rufuspollock** [comment]
@aaronkaplan depends what you mean by small. The original data is over a billion rows. The data in the main site database is ~12M rows in the main table so is a substantial size -- I consider 12M still fairly large for frontend DBs.

**Comment by zelima** [comment]
@rufuspollock @aaronkaplan going to downgrade to one lower size - `db.m4.large`

**Comment by zelima** [comment]
@rufuspollock @aaronkaplan currently we are on `db.m4.large`. 
A queries got a bit slower, but still fast enough for loading all the data for graphs on country and AS pages.

Closing for this sprint we can reopen later if needed

**Comment by aaronkaplan** [comment]
> On 19 Feb 2017, at 09:56, Irakli Mchedlishvili <notifications@github.com> wrote:
> 
> @aaronkaplan Yes RDS only for aggregated.
> 
> Well our main fact table has ~14,000,000 rows for now and definitely not enough .615gb (the one we used to have). Agree that 16 GB may be too much.

No...

just for the record. 14 million entries is not much in a postgresql DB.
It's just simply not tuned. Have been running PQs with TBs of data.

**Comment by aaronkaplan** [comment]
reopening. RDS is terribly slow. 
If you don't know how to tune postgresql, feel free to ask me.

**Comment by rufuspollock** [comment]
@aaronkaplan I'd like to suggest that you open a new issue if we still have improvements we can make to RDS as it will make things much easier to follow. I've done this here:

https://github.com/cybergreen-net/stats-new/issues/272
