### ISSUE TITLE
Integrate UI changes for source of infection on Country page

### ISSUE THREAD

**Issue by zelima** [cybergreen-net/stats-new#175]
stacked bars indicating source of infection for country show on the right of the page is live

## improvements before deployed:

* [x] https://github.com/cybergreen-net/cg-graphs/issues/49

* [x] Top of page should have a title (h1) e.g. "AS France - {number} full title"
* [x] LHS Graphs have heading at top of page (e.g. h2): "Country Comparison" and RHS has "AS Source"
  * [x] Above dropdown
* [x] Dropdown redirect seems to have a bug ... (goes to 401)

**Comment by anuveyatsu** [comment]
FIXED in https://github.com/cybergreen-net/stats-new/pull/178
