### ISSUE TITLE
Listing risks for which there's no data

### ISSUE THREAD

**Issue by GregoryRhysEvans** [cybergreen-net/stats-new#18]
Do we want to have a column for a risk for which no data exists?

For example: there is (currently) no data for spam, leaving empty columns on the, eg, [place page](http://cybergreen-stats.herokuapp.com/place) and [place/{place-id} pages](http://cybergreen-stats.herokuapp.com/place/belgium/)

**Comment by aaronkaplan** [comment]
no, please remove

**Comment by GregoryRhysEvans** [comment]
This has been removed

**Comment by aaronkaplan** [comment]
confirmed. fixed.
