### ISSUE TITLE
[Epic] Download option on AS and country pages

### ISSUE THREAD

**Issue by zelima** [cybergreen-net/stats-new#182]
User epic: 
> As a National CERT I want to download the data so I can intergrated to my own system

See all [User Stories](https://docs.google.com/document/d/1TZ-q_45AsGmxU5ywSNkc6iokGFnyXtkbBSWOl75zr6I/edit#heading=h.a8ea4jnbk95b)

## Proposed Solution

- Have a button at the bottom of the page that download data in CSV format
  - On Country page have two download buttons:
    - One on LHS: download all the data over time for that country (all risks -- excluding maybe DDOS which is complex). Can we get that from the API? **If not**:  put a button/link for each risk one at a time e.g. "Open NTP"
    - One on RHS: not super clear what we want to download for AS so here put a link to download page with title like: "Get AS data on the Download page"
  - On the AS page: one download button to download all the data on that AS over time (i.e. all risks together)
- CSV should have data sorted by date DESC containing columns:
  - Country page: `date,risk,country,count,count_amplified,count_normalized` - not sure of last two (include last two for now)
  - AS page: `date,risk,country,as,count,count_amplified,count_normalized`

#### questions

- Should we serve API for this? Eg: `api/count_by_country?country=gb&...&format=csv`
  - Ans: yes
- R: should we just route people to the download page or give them a form on each individual page?
  - Ans: give them direct download if we can.

## Tasks

- [x] support `?format=csv` &   `?filename=name` #79 [3]   
  - filename by default - `cg-statistics.csv`
  - will be ignored if `?drilldown=as` is provided
  - will be ignored if there is no result - Will return JSON `{total:0, result:[]}`
  - outputs CSV with headers eg: 
  ```
  date,risk,country,count,count_amplified 
  2017-01-01,1,country,1,3 
  ```
- [x] create buttons on country and AS pages https://github.com/cybergreen-net/cg-graphs/issues/59
- [x] deploy

**Comment by rufuspollock** [comment]
@zelima my question is whether we just root people to the download page or give them a form on each individual page.

One idea is to have a little JS widget that we can embed in both download page and individual pages  (e.g. country page). The widget can be customized so that on the country page it is preconfigured to only download data for that country.

Note: also #79 is probably a pre-requisite for this.

**Comment by zelima** [comment]
FIXED 
https://cybergreen-staging.herokuapp.com/country/united-kingdom/
https://cybergreen-staging.herokuapp.com/country/united-kingdom/asn/5413
