### ISSUE TITLE
proposal for y-axis scale for ASN distribution in country/ page

### ISSUE THREAD

**Issue by aaronkaplan** [cybergreen-net/stats-new#187]
So, since we have a typical long tail distribution of risks over ASNs, I highly suggest we take a log scale y-axis on the graphs on the right side of the countries page.

Pro:
  * This way, you can see clearer the different ASNs .
Con: 
  * non visually intuitive

What do you think?
The problem really is that we have a huge "Rest" part and a very small part of real ASNs.

Example: https://cybergreen-staging.herokuapp.com/country/united-states/
Open NTP graph.

Other idea: change the color coding. This way the difference between different stacks of the stacked bar graph are easily visible.

**Comment by rufuspollock** [comment]
@aaronkaplan definitely worth thinking about.

The main reason we have gone with simple counts is to keep a "shape" connection with the plot on the LHS (i.e. we intend that the shape of bars on RHS match the shape of line for country on LHS).

**Comment by aaronkaplan** [comment]
---
Mobile

> On 24 Feb 2017, at 01:19, Rufus Pollock <notifications@github.com> wrote:
> 
> @aaronkaplan definitely worth thinking about.
> 
> The main reason we have gone with simple counts is to keep a "shape" connection with the plot on the LHS (i.e. we intend that the shape of bars on RHS match the shape of line for country on LHS).
> 

Yeah makes sense. How about the idea of using a different color scheme on the right in order to be able to distinguish the ASNs  from each other?

**Comment by zelima** [comment]
moving to current milestone 
@rufuspollock can we make decision here?

**Comment by rufuspollock** [comment]
WONTFIX I think atm. @aaronkaplan feel free to re-open if you think differently.
