### ISSUE TITLE
Add explanation page for metrics and their calculation

### ISSUE THREAD

**Issue by zelima** [cybergreen-net/stats-new#195]
To complete this we need description that should be provided by CyberGreen as written in SOW.

@ataslim could you please lead on providing the text

**Comment by ataslim** [comment]
@zelima [here is the text](https://docs.google.com/document/d/1S9zED0qdVZB0YfvD0zZFaYr0ki2MZI_B2NbvSCU0vh8/edit?usp=sharing) for the metrics description that we can use. Per our conversations with @rufuspollock and Yurie's walkthroughs with @shiweiart, the stats site needs to be more explanatory for any visitor (e.g. policymaker) as you navigate throughout. That means, as a policymaker, I should more fully understand what it is that I'm looking at (with respect to visualizations, for example) on each page.

**Comment by rufuspollock** [comment]
@ataslim do you have any thoughts where you want this to go? Should it be on stats site or www site (we will of course link it from stats website wherever it goes)

**Comment by zelima** [comment]
@ataslim I added the new page with content. https://cybergreen-staging.herokuapp.com/metrics
Please checkout and share your thought.

If it's ok we can close

**Comment by zelima** [comment]
FIXED. 
reopen if needed
