### ISSUE TITLE
API improvements

### ISSUE THREAD

**Issue by zelima** [cybergreen-net/stats-new#20]
* [x] `/api/v1/count`
  * [x] ?asn
  * [x] ?start and end
* [x] `/api/v1/country/{id}.`
* [x] `/api/v1/asn/{id}`
* [x] Have `/api/count, /api/country/, /api/asn` redirect to `/api/v1/...`

**Comment by rgrp** [comment]
I propose we leave country and asn since these are just data already in the CSV files from reference sources. Little value in having them in the API other than completeness. We can revisit these later if need be.

**Comment by aaronkaplan** [comment]
I don't agree.
I tested these and they dont' work and I think it should be part of BETA-2. There is a value in that.

- [x] /api/v1/count_by_country works
- [ ] /api/v1/count -> error message
- [ ]  /api/v1/country/AT -> error message: "Cannot GET /api/v1/country/AT"
- [ ] /api/v1/asn/35492 -> error message
- [ ] /api/count does not redirect to /api/v1/count 

Please fix.
I moved this issue to post-Sept-30 fix-ups, ok?

**Comment by rgrp** [comment]
@aaronkaplan all country ids must be lower case.

@zelima can you please look at this ...

**Comment by zelima** [comment]
@aaronkaplan What should this two result?
```
 /api/v1/country/AT -> 
/api/v1/asn/35492 -> 
```
same asd
```
 /api/v1/country?id=at
api/v1/asn?asn=35492
```

**Comment by rgrp** [comment]
@zelima yes - but REST style would meaning having the id in the url

**Comment by zelima** [comment]
@rgrp Ok, so redirection /api/v1/country/AT -> /api/v1/country?id=at would be useless here
