### ISSUE TITLE
Choropleth map back on the front page

### ISSUE THREAD

**Issue by zelima** [cybergreen-net/stats-new#209]
Mock Up
![image](https://cloud.githubusercontent.com/assets/15143785/23663010/bc219478-036a-11e7-9a7e-db8230bbd694.png)

Choropleth map will be reimplemented on the front page using the Plotly library (in React). To do so we will need to create a new component (e.g. ChoroplethMap.js) and async actions (with corresponding reducers) for getting required data. Plotly's choropleth map requires having either country names or country codes in ISO-3. We have country names and can use it (assuming plotly is case insensitive and country names match).

#### API
API path: `/api/v1/count_by_country?start=YYYY-MM-DD&risk=x&limit=500&granularity=month`
Response body:
```
{
  "total": 238,
  "results": [
    {
      "risk": x,
      "country": "country ID",
      "date": "YYYY-MM-DD",
      "count": count
    },
    ...
  ]
}
```

#### Getting data for other dates (by default we load the latest available month)
* We may need a list of dates and risks passed from the server. This way we can use them as options when a user selects a new date or risk from a dropdown/searchbox element.
* We could have separate dropdowns/searchboxes for year, month and day. Or we can just reformat date to make it more readable (16 January 2017). 
* We need a submit button, which triggers onSubmit method and dispatches async action.

#### ChoroplethMap component - https://github.com/cybergreen-net/cg-graphs/issues/73
1) `drawChoroplethMap` method for rendering the map;
2) `convertToPlotlySeries` method for converting raw data into Plotly format;
3) Form element with `date` and `risk` options;
4) `onSubmit` method for form element to dispatch actions to get data;
5) `componentDidMount` method to dispatch action to get data with the latest date and DDOS;
6) `componentWillReceiveProps` method to handle received data;
7) `computeState` method to handle which dataset to display;
8) `selectedDateAndRisk` method to track which date and risk a user selected - dispatch actions for getting data here and also action for updating the state;
9) handle caching data.

#### Actions and reducers - https://github.com/cybergreen-net/cg-graphs/issues/74
1) `ChoroplethMapActions.js` to have async action called `fetchMapData` - use `/api/v1/count_by_country?date=YYYY-MM-DD&risk=x`;
2) Have `FETCH_MAP_DATA_REQUEST`, `FETCH_MAP_DATA_SUCCESS`, `FETCH_MAP_DATA_FAILURE` action creators;
3) Create reducers for these actions;
4) Create methods for checking if data is cached.

#### Redux store
```
{
  entities: {
    ...
    cubeByRiskByDate: {
      riskId: {
        date: [
          {
            risk: riskId,
            date: date,
            country: countryName,
            count: count
          },
          ...
        ]
      }
    }
  }
  ChoroplethMapViews: {
    risk: DDOS // this is updated when a user selects another risk
    date: latestDate // this is updated when a user selects a new date
  }
}
```

- [x] integrate and deploy https://github.com/cybergreen-net/stats-new/issues/227

**Comment by zelima** [comment]
Map deployed on staging website.
For now missing redirection to country when clicked and probably some color fixes

**Comment by rufuspollock** [comment]
Largely FIXED: https://cybergreen-staging.herokuapp.com/

Quick comments:

* Can we make this really big - like full-width of screen and appropriately high?
* Heading should be same style as Global DDOS above
* Colour: do we want it to change for different risks? What is the right colour?
* Title and description need along with explanation of the scale -- probably part of #205

**Comment by zelima** [comment]
FIXED moving remaining issues to https://github.com/cybergreen-net/stats-new/issues/200
