### ISSUE TITLE
Configure map visualizations

### ISSUE THREAD

**Issue by zelima** [cybergreen-net/stats-new#21]
* [x] Hardcoded for demonstation 
* [ ] Automated, showing latest -1 week

**Comment by rgrp** [comment]
This will be post 30th now ...

**Comment by aaronkaplan** [comment]
confirmed.

**Comment by aaronkaplan** [comment]
Summary : we need to add a time slider / ("previous week" / "next week") arrows for *all* pages.

**Comment by rgrp** [comment]
@aaronkaplan please open a separate issue for that. This issue is not about that ;-) (and i agree we need something generic ...)

**Comment by rgrp** [comment]
@aaronkaplan I've created #84 for time slider for all visualizations
