### ISSUE TITLE
Country page "slow"

### ISSUE THREAD

**Issue by zelima** [cybergreen-net/stats-new#210]
Loading `country/country-id` page takes too much time.

### task

- [x] Determine why
  - is it RDS
  - Is it Heroku 
  - CG API is slow ? 
    - Test how fast olap cubes API is https://github.com/zelima/cg-cubes

**Comment by zelima** [comment]
I've tried to retrieve the same exact information using [cg cubes API](https://cg-cubes.herokuapp.com) and [current cg API](https://cybergreen-staging.herokuapp.com/api/v1/count_by_country). 
Both of them are using same RDS instance and same database - meaning everything is same - tables, 
indexes, constraints, etc...

Results of tests:

#### Query to get number of infected devises for given risk in given country over time (Heroku):
- cubes API: https://cg-cubes.herokuapp.com/cube/fact_count/aggregate?cut=risk:1|country:GB&drilldown=dim_date:week_start  -  4.50s
- current API: https://cybergreen-staging.herokuapp.com/api/v1/count_by_country?limit=500&country=GB&risk=1  -  1.45s

#### Query to get number of infected devises for given risk in given country over time (My machine -localhost):
- cubes API: same query  -  3.66s
- current API: same query  -  2.98s


#### Query to get number of infected devises for given risk in given country for given AS over time (Heroku):
- cubes API: https://cg-cubes.herokuapp.com/cube/fact_count/aggregate?cut=risk:1|country:GB|asn:5413&drilldown=dim_date:week_start  -  1.61s
- current API: https://cybergreen-staging.herokuapp.com/api/v1/count_by_country?limit=500&country=GB&risk=1&asn=5413  -  1.46s

#### Query to get number of infected devises for given risk in given country for given AS over time (My machine - localhost):
- cubes API: same query  -  947ms
- current API: same query  -  1.22s

**Comment by zelima** [comment]
As a conclusion can say for sure that current CG API works fine. In some cases even better than OLAP cubes API.

Thought time for single call is <5 seconds using CG API, when actually loading the page (page with graphs, not just json) each API call takes ~6 seconds and even thought the API calls are made asynchronously, overall time for retrieving whole data is around >15 seconds

**Comment by rufuspollock** [comment]
@zelima so i guess my question here was not comparison with cubes vs current main api -- they are both driven off DB and heroku apps so should be similar.

Main question: where is time being taken in the stack. Is it:

* Heroku
* NodeJS app
* DB calls
* Number of different calls

**Comment by zelima** [comment]
@rufuspollock updating with screenshots of networks of page loaded with both - heroku and my machine

- heroku 
![heroku](https://cloud.githubusercontent.com/assets/15143785/23602851/eb8d4ca2-026b-11e7-88a9-82e00d84b527.png)

- my machine 

![localhost](https://cloud.githubusercontent.com/assets/15143785/23602859/f3861ab0-026b-11e7-8957-01a21f321d12.png)

**Comment by rufuspollock** [comment]
FIXED. I think our analysis is done. Looking at local vs heroku we see a 4-5x speedup which suggests that Heroku may be a bottleneck.

My sense here is that this is probably worth doing bit to do with Heroku and we should ask CG about upping the dynos here to do an experiment and see if that improves things (and open a separate issue for this).

**Comment by aaronkaplan** [comment]
Rufus could you lay out the details that you see when moving this off of heroku?

Best,
A.

---
Mobile

**Comment by aaronkaplan** [comment]
So, let's please re-open this issue since it's not *fixed* yet. Let's please close it when we tried out more dynos and see if it goes better. okay?

**Comment by zelima** [comment]
@aaronkaplan This issue was for analyzes and that is done. 
I opened new issue for better tracking https://github.com/cybergreen-net/stats-new/issues/258
