### ISSUE TITLE
Add heroku dynos to speed up the stats website

### ISSUE THREAD

**Issue by zelima** [cybergreen-net/stats-new#229]
Reason [country page](https://cybergreen-staging.herokuapp.com/country/united-kingdom) is slow, may be the heroku as discussed https://github.com/cybergreen-net/stats-new/issues/210

So for speeding up we may need more heroku [dynos](https://devcenter.heroku.com/articles/dynos). 

We can do an experiment and see if that improves things

**Comment by zelima** [comment]
@rufuspollock Heroku says
> Heroku apps running on Professional-tier dynos (any dyno type except Free or Hobby) can be scaled to run on multiple dynos simultaneously.
Currently we are running on free
```
=== web (Free): node app.js (1)
web.1: up 2017/03/09 17:32:07 +0400 (~ 18m ago)
```

So my guess is we need to upgrade dyno type to at least `standard-1x`. more info https://devcenter.heroku.com/articles/dyno-types

**Comment by rufuspollock** [comment]
@zelima I suggest we create an account as per discussion.

**Comment by zelima** [comment]
New account is created and applications transferred to that account.
Email is sent to @YurieIto Login and password info.
Also there's explanation how to add credit car  so we are able to add some more dynos for our applications

**Comment by aaronkaplan** [comment]
how many? prices scales up per dyno

**Comment by zelima** [comment]
Currently staging website is running `web at 3:Standard-1X `

**Comment by rufuspollock** [comment]
@zelima is there any noticeable effect? Please comment and close either way - perhaps a link to a follow up issue that reminds us to review this in two weeks or so.

**Comment by zelima** [comment]
No significant changes! I switched to `Standard-2X` (and switched to use dynos for production app and not for staging)

To follow up see https://github.com/cybergreen-net/stats-new/issues/258
Closing as FIXED

**Comment by aaronkaplan** [comment]
adding more dynos does not make the code be more efficient.

**Comment by rufuspollock** [comment]
@aaronkaplan yes, and we'd discussed this solution after doing quite a bit of analysis in a separate issue #210.
