### ISSUE TITLE
Weights of open NTP and open recursive DNS might be switched

### ISSUE THREAD

**Issue by aaronkaplan** [cybergreen-net/stats-new#232]
pls. check. I 'll add a detailed description.

**Comment by aaronkaplan** [comment]
So, I promised some details.

Here is what I found:
open recursive DNS has an amplification factor of 41 only. Whereas NTP has ~ 500.
So, I'd expect recusrive DNS to now have such a huge influence on the DDOS curve.

Take a look at https://cybergreen-staging.herokuapp.com/country/austria

DDOS curve:
![image](https://cloud.githubusercontent.com/assets/750019/23834178/57e635e0-0752-11e7-98bf-9f737ec64a85.png)

Observe the jump at ~2015/4/1

Now let's look at the different risks - what happened during 2015/4? 

![image](https://cloud.githubusercontent.com/assets/750019/23834207/d925a2e4-0752-11e7-9688-1fb12f3767ac.png)


Please observe that the only risk which suddenly has data again (it was missing) around that time is open recursive DNS. This however generates a large increase in the DDOS chart. Which somehow cant' be the case if y ou look at the amplficiation factors and the absolute counts of vuln. devices for each risk

Therefore -> something is wrong in the way the DDOS chart is calculated. 

Please inspect.

**Comment by zelima** [comment]
FIXED see https://cybergreen-staging.herokuapp.com/country/austria/ for example.

Note for self: This was caused by showing simple counts for **all** risks (including DDOS) instead of showing simple counts for "simple" risks and **amplificated** count for DDOS
