### ISSUE TITLE
map: no units shown on hover

### ISSUE THREAD

**Issue by aaronkaplan** [cybergreen-net/stats-new#237]
In the new map, (https://cybergreen-staging.herokuapp.com/) it would make sense to actually show the units when you over over a country.
(Just showing a number is not useful). I'd exepct something like "the US has a DDoS potential of 1 TBit/sec" or so

Update as per discussion:

- default unit  - MBit/sec - `max(n) < 1000`  - divide by 1
- GBit/sec - `1000 < max(n) < 1000000` - divide by 1000
- TBit/sec -  `max(n) > 1000000` - devide by 10^6

where n in AF count

**Comment by zelima** [comment]
@aaronkaplan should we do TBits/sec or GBit/sec as on chart?

**Comment by zelima** [comment]
@aaronkaplan also what bout other risk - what should they sat?

**Comment by aaronkaplan** [comment]
@zelima: it depends on the size of the curve of course.
Please remember the formula:

<a href="https://www.codecogs.com/eqnedit.php?latex=risk_j(ASN_i)&space;[\texbf{MBit/sec}]&space;=&space;\left&space;(&space;\sum_{j=1}^{N}{AF(risk_j)*&space;count&space;devices(ASN_i)}&space;\right)&space;*&space;1&space;[\textbf{MBit/sec}]" target="_blank"><img src="https://latex.codecogs.com/gif.latex?risk_j(ASN_i)&space;[\texbf{MBit/sec}]&space;=&space;\left&space;(&space;\sum_{j=1}^{N}{AF(risk_j)*&space;count&space;devices(ASN_i)}&space;\right)&space;*&space;1&space;[\textbf{MBit/sec}]" title="risk_j(ASN_i) [\texbf{MBit/sec}] = \left ( \sum_{j=1}^{N}{AF(risk_j)* count devices(ASN_i)} \right) * 1 [\textbf{MBit/sec}]" /></a>

**Comment by aaronkaplan** [comment]
@zelima what about the other risks ? (Mirai)? Well - this is a different category. There the units can not be given in {T,G,M}Bits/sec.
Only counts.

**Comment by rufuspollock** [comment]
@zelima these should follow same naming for all other graphs (i.e. use the units description from the risks table). I also suggest that if we have "scaling" numbers we put those into the risk table as well so we have *one* central location where they get set. (ie. for DDOS we'd have a column with e.g. 1000000 if we divide by 1000000 to get to the relevant units we describe in the unit columns from the raw counts).

**Comment by aaronkaplan** [comment]
@rufuspollock also possible. What do you think of staying with Bits/sec as a base unit and then divide by the scaling factor?

**Comment by zelima** [comment]
FIXED show relevant unit on map hover  + on any graph Ylabel

**Comment by aaronkaplan** [comment]
There is a problem with the formula. Not Atomatic's fault but mine.
We assume a maximum of 1 MBit/sec *upstream* capacity per device. So... actually it must be capped at count(devices).
This formula - as it is now - assumes that there is no upper limit on upstream.
That's wrong.

--> Atomatic, we'll revisit this and will have to adjust.

**Comment by zelima** [comment]
@aaronkaplan As I understood the new problem is that Units are wrong, cause **formula** is wrong. Can we have new issue for that and close this one as it is about not having Unit at all and that is fixed

**Comment by zelima** [comment]
Closing. Please open New issue in relevant milestone

**Comment by aaronkaplan** [comment]
No actually I am re-opening this issue.
Why?
Because the formula was wrong does not mean that the units were wrong.
We will fix the formula but the units will remain.

**Comment by aaronkaplan** [comment]
Are all units versus data fixed now?
@rufuspollock I need you to do some cross checks please. This is the most important thing here for a release.

**Comment by rufuspollock** [comment]
@aaronkaplan i'm closing. We believe this is fixed -- and was fixed when @zelima said the issue **was** fixed above.
