### ISSUE TITLE
Set up development database separate from production database

### ISSUE THREAD

**Issue by rgrp** [cybergreen-net/stats-new#24]

**Comment by zelima** [comment]
@rgrp Instructions for development database is inside README.md and it is populated by `aggregate.py`, separately from production database. Do we need anything more besides this?

**Comment by chorsley** [comment]
Related: any processing scripts need to draw clean files from the correct location, e.g. /dev/clean/ or /prod/clean/. 

This should be configurable by env var / switch - it currently appears to be hardcoded to /dev/ in https://github.com/cybergreen-net/aggregator/blob/master/load/main.py. The same setting should set both the source S3 path and the DB to output to.

**Comment by rgrp** [comment]
I think this can now move to infrastructure repo

**Comment by zelima** [comment]
Moved to https://github.com/cybergreen-net/aggregator/issues/20
