### ISSUE TITLE
main site: drop down below the world map does not work

### ISSUE THREAD

**Issue by aaronkaplan** [cybergreen-net/stats-new#248]
The left drop down just below the world map on the start page only allows you to select one single date.

**Comment by zelima** [comment]
This is not a bug, this is expected behavior, As we decided to display data for only latest month.
We will implement this with option to switch time granularity

**Comment by aaronkaplan** [comment]
then please in the meantime do not display this drop down box.
Otherwise people would assume it works, but it does not currently.
ok?
:)

**Comment by zelima** [comment]
FIXED. removed date selector for now
