### ISSUE TITLE
Deploy staging to production for March 2017 release

### ISSUE THREAD

**Issue by aaronkaplan** [cybergreen-net/stats-new#249]
- [x] As discussed via email "stats.cybergreen.net" shall be pointing to the (current) staging site.
 - [x] switch heroku dynos  from staging app to sactual production app 
 - [x] Please switch on the 16th of March.
 - [x] Test every link !

**Comment by zelima** [comment]
FIXED Deployed see stats.cybergreen.net

**Comment by aaronkaplan** [comment]
Where is the old site?

**Comment by rufuspollock** [comment]
@aaronkaplan we no longer have it in this case. We did not realise there was a requirement for it in this case.
