### ISSUE TITLE
global map : mouse over tooltips are confusing

### ISSUE THREAD

**Issue by aaronkaplan** [cybergreen-net/stats-new#250]
It's not clear what the numbers are when you move your mouse over the map.
Are these count of #risk for a country? Are these GBit/sec DDoS impact?
I'd say it makes the most sense to show counts here.
But please make it clear (legend below the map?) that you are showing counts here.

**Comment by zelima** [comment]
FIXED displays TBit/sec (or relevant) in case of DDOS. Count of infected "infected/vulnerable" devices in case of other

**Comment by aaronkaplan** [comment]
Still a bug.
Try switching from DDOS to Mirai.
Then switch back to DNS.

units are wrong again in the tooltip.

**Comment by zelima** [comment]
@aaronkaplan I either ca not reproduce this error or need more clarifications. 
On USA example: 
Default - DDOS - > `1,587 TBit/sec DDOS potential in US` 
Switch to MIrai - > `52,678 Count of Infected devices in US`
Switch to DNS - > `2,585,757 Count of Vulnerable devices in US`

**Comment by zelima** [comment]
In fact I discovered other bug:
Select Any risk, than DDOS again. Is saying `undefined DDOS potential...` 
Now it is FIXED

**Comment by zelima** [comment]
Closing. Please open **new** issue in next milestone if there is remaining anything

**Comment by aaronkaplan** [comment]
No, it's actually not fixed.

Take a look at this screenshot.
![image](https://cloud.githubusercontent.com/assets/750019/23994004/3315834e-0a43-11e7-8635-4be546cc9f5e.png)

Select "Mirai" -> hover over the US -> "count"
Select SSDP again -> hover over the US -> "count"

Somehow you don't seem to read the units from the risks.csv file and display accordingly. Can this be the reason?

**Comment by zelima** [comment]
@aaronkaplan no, code is using `risk.csv`. 
Can you actually explain what is wrong here? 
- Mirai should not say "count"? 
- SSDP should not say "count"?

in `risk.csv` both have count as measurement units https://github.com/cybergreen-net/refdata-risk/blob/master/data/risk.csv

**Comment by aaronkaplan** [comment]
Ah!
okay, the risk.csv does indeed say count.
D*mn, so it really depends on the context apparently.
Okay, then let's keep it as it is for now. I'll have to think about that some more.
Closing and will re-open another one once I know how to handle the context (map versus table).
