### ISSUE TITLE
favicon: is this (book icon) the one that we want?

### ISSUE THREAD

**Issue by aaronkaplan** [cybergreen-net/stats-new#255]
I believe there is a small version of the CG logo somewhere?

@YurieIto ? @ataslim ? Do we have a small CG logo?

**Comment by ataslim** [comment]
Not that I know of. I think the best I can do is this

![cg globe](https://cloud.githubusercontent.com/assets/22147924/24196781/6feb4088-0ed5-11e7-81fc-40fc81cf7f10.png)

**Comment by zelima** [comment]
FIXED
