### ISSUE TITLE
bug in antarctica?

### ISSUE THREAD

**Issue by aaronkaplan** [cybergreen-net/stats-new#256]
If you go to https://cybergreen-staging.herokuapp.com/country/antarctica/asn/204136
the page will load for ever. 

Is that a bug when there is no data for an ASN ?

**Comment by zelima** [comment]
@aaronkaplan There was small bug with spinner that is fixed, but this actually led to discover bigger problem. I opened separate issue for discussion https://github.com/cybergreen-net/refdata-asn/issues/2

**Comment by zelima** [comment]
FIXED. Loading data and showing "Unknown" if reference data is not present

**Comment by aaronkaplan** [comment]
thx
