### ISSUE TITLE
please review *all* units and scaling factors

### ISSUE THREAD

**Issue by aaronkaplan** [cybergreen-net/stats-new#260]
@rufuspollock I am going to assign this to you.
I did some cross checks and the units (or the division scaling factors) are wrong.

I checked for the Norfolk islands.
https://cybergreen-staging.herokuapp.com/country/norfolk-island/

In this case it's simple enough to calculate by hand on a piece of paper.
The DDOS graph below on the Norfolk Island page is off by a factor of 1000.

--> please review *all* places where we have graphs/maps where GBit/sec or TBit/sec are shown.
Check with a piece of paper / calculator please.

**Comment by aaronkaplan** [comment]
![image](https://cloud.githubusercontent.com/assets/750019/23955536/713e607c-099a-11e7-9e8e-034f0a471671.png)

**Comment by zelima** [comment]
FIXED

**Comment by aaronkaplan** [comment]
@rufuspollock please review and only then after you checked, close the issue. I'd like to get the "yes, I as product owner checked it"

**Comment by rufuspollock** [comment]
FIXED. I've checked and the ones I can see look correct.
