### ISSUE TITLE
map: for visual clarity, might make sense to route the color ramp function through a log() ?

### ISSUE THREAD

**Issue by aaronkaplan** [cybergreen-net/stats-new#266]
@rufuspollock , it might make (visual) sense to do a log() over the score of the countries in the map.
Otherwise everything looks very similar (colors).

What do you think about this?

color(country) = colormaplookup(log(score(DDoS potential)))

**Comment by zelima** [comment]
They already are logs: https://github.com/cybergreen-net/cg-graphs/blob/master/src/components/ChoroplethMap.js#L105

**Comment by zelima** [comment]
FIXED/INVALID this was already done when issue was open. Feel free to re-open if anything is remaining
