### ISSUE TITLE
Numbers in country table are wrong

### ISSUE THREAD

**Issue by aaronkaplan** [cybergreen-net/stats-new#269]
These numbers can not true.
Please have a look if there is a hidden copy & paste bug for the _source of the columns_.

![image](https://cloud.githubusercontent.com/assets/750019/24075131/ecb0f2a6-0c15-11e7-9916-091cdbb2b2d4.png)

**Comment by zelima** [comment]
For some reasons we have same raw data for NTP and DNS in first three weeks of 2017.
See discussions here https://github.com/cybergreen-net/pm/issues/100
