### ISSUE TITLE
track downloads of training materials

### ISSUE THREAD

**Issue by zelima** [cybergreen-net/stats-new#275]
We want to track downloads for PDF files on `mitigation/` and `mitigation/asean/` pages on http://www.cybergreen.net

## Acceptance criteria 

- [ ] Use google analytics to track clicks on the download links (User will not need to enter any contact information)
- [ ] all 4 files are tracked on both of pages 

## Tasks

- add JS code for tracking downloads on `mitigation/` and `mitigation/asean/` appropriate pages

Useful reading https://support.google.com/analytics/answer/1136920?hl=en

**Comment by rufuspollock** [comment]
@zelima looks good. One suggestion: I think is more of an issue re the www repo rather than stats-new so might be better there.

**Comment by zelima** [comment]
@rufuspollock True closing as DUPLICATE. moved to https://github.com/cybergreen-net/www.cybergreen.net/issues/71
