### ISSUE TITLE
!! important UI request pre Sept-30: add visual "BETA-2" tag

### ISSUE THREAD

**Issue by aaronkaplan** [cybergreen-net/stats-new#28]
Hi,

It's important to note on the current site that this is still BETA-2.
Otherwise people will interpret the current data as trustworthy and might start wondering.
Can we have a clear visual ribbon/tag "BETA-2" somewhere on every page?

Maybe even make a small separate page describing that this is not the final product yet.
You can come to that page by clicking on the tag/ribbon.

Thanks!

**Comment by GregoryRhysEvans** [comment]
@aaronkaplan I have updated the logo to make it clearer and re-added the explanatory text on the main page from the old site, so visitors will know it is a beta.

**Comment by aaronkaplan** [comment]
> On 29 Sep 2016, at 10:06, GregoryRhysEvans <notifications@github.com> wrote:
> 
> @aaronkaplan I have updated the logo to make it clearer and re-added the explanatory text on the main page from the old site, so visitors will know it is a beta.
> 

Thanks Greg. However, could we have a "BETA-2" ribbon there? Or at least the current "beta" text should be
a) "beta-2" or capitalised "BETA-2" and a slightly more noticeable color  or...
b) a real ribbon. Example: bettercrypto.org "fork me on github"

The reason behind it is that I visually clearly want to show people that this version is not the final version.
We get lots of questions of people asking why the data for country XY or ASN xyz is like this. The answer is that we still have bugs and also that the data does not lend itself to proper comparisons with other data sources (yet).
So, we are beta. We want to get their feedback on the site however.
Otherwise visitors / end users might dismiss the whole project quickly.

So that is why it's important.

Thanks!

**Comment by GregoryRhysEvans** [comment]
@aaronkaplan Sorry, my changes were not pushed to heroku and so weren't live just now :)

Have a look now.

**Comment by aaronkaplan** [comment]
> On 29 Sep 2016, at 10:25, GregoryRhysEvans <notifications@github.com> wrote:
> 
> @aaronkaplan Sorry, my changes were not pushed to heroku and so weren't live just now :)
> 

Ahhh!


> Have a look now.
> 
I see it now. Thanks.
Visually quite heavy (bold face? or too big of a font size or CAPS was not such a good idea? ... don;t know) ;-) but at least you can't miss it now! Yeah.

@rgrp: do we still have the old site somewhere or could we spin it up?
Because I have the feeling we discussed many of these topics already with the old site and we actually solved it back then.

Might save some work

**Comment by rgrp** [comment]
@aaronkaplan old site is still live at http://stats.cybergreen.net/

**Comment by aaronkaplan** [comment]
Yeah. Figured out shortly afterwards. Np

---
Mobile

**Comment by aaronkaplan** [comment]
confirmed. fixed.
