### ISSUE TITLE
Most recent data only shows "rest" for AS source

### ISSUE THREAD

**Issue by ataslim** [cybergreen-net/stats-new#286]
No distribution of AS sources, just "rest" for most recent data.

![screen shot 2017-05-14 at 9 39 34 am](https://cloud.githubusercontent.com/assets/22147924/26034358/516f9cc0-3889-11e7-8ea9-137690b212df.png)

**Comment by aaronkaplan** [comment]
Can you pls. check if the IP2ASN process failed?

**Comment by kxyne** [comment]
Confirmed it's all correct in the ETLed file (hence no alert), it's something in aggregation but I can't see what, will look into it tomorrow.

**Comment by kxyne** [comment]
2017-05-09 09:53:28 - /home/cybergreen/etl2/aggregator/main.py:473 (update_dim_asn_if_entry_does_not_present) -
Warning: New AS numbers in fact table that do not present in asn dimension.
Updating dim_asn as follows:

number    | title   | country
----------+---------+--------
2017-05-09 09:53:28 - /home/cybergreen/etl2/aggregator/main.py:486 (update_dim_asn_if_entry_does_not_present) - 328096    | unknown | UG
...
It definitely thinks it ran successfully and the update_dim_asn_if_entry_does_not_present function found 1019 "unnamed" ASN, which means it read the file correctly.

**Comment by zelima** [comment]
FIXED. This  was a bug in logic - comparing end and start dates from API to the dates of entries from fact count. 

Entries from fact_count may have dates of any time of week, Eg: if scan was made on last Friday it would have date - `2017-05-13`. As we yet displaying 2nd latest week from database, auto calculated end date would be last Monday ` 2017-05-08`. So in the logic part script was ignoring everything > `2017-05-08` - all the scans made it previous wee but monday
