### ISSUE TITLE
UI regression: ASN numbers dont' show in the country page

### ISSUE THREAD

**Issue by aaronkaplan** [cybergreen-net/stats-new#33]
In the table of the ASNs per country, the link to the ASN detailed stats (trendline etc) is white on white.

**Comment by aaronkaplan** [comment]
Pressed reload and it's fine now. Might be a temporary Chrome bug ?

**Comment by zelima** [comment]
Did this repeat? 
can we close?

**Comment by aaronkaplan** [comment]
---
Mobile

> On 30.09.2016, at 16:41, Irakli Mchedlishvili <notifications@github.com> wrote:
> 
> Did this repeat? 
> can we close?
> 

I'll re-test.

**Comment by aaronkaplan** [comment]
looks ok. seems fixed.
