### ISSUE TITLE
U{I,X} improvements post Sept-30 check-list

### ISSUE THREAD

**Issue by aaronkaplan** [cybergreen-net/stats-new#34]
- [x] in the ASN page (with time series), it would be great to have 12 sub-tics to allow to find the month. Right now, we only have one major tick per year. It's hard to visually find the month in the time series.
- [x] Make the world map taller. See #30 
- [x] time series: visually distinguish between 0 and missing values. Maybe bar graphs?
- [x] time series: allow for hovering over the time series line to see the value

**Comment by zelima** [comment]
@aaronkaplan referring to ASN comparisons:
- Where should this happen, on which page?
-  How many ASN's may/should be compared? 2? more?
- Should this be graph? table?

**Comment by rgrp** [comment]
@zelima ASN comparison is just an idea for discussion and now split out to #100

**Comment by rgrp** [comment]
FIXED. (Some time ago - big items are split out).
