### ISSUE TITLE
regression: rank missing

### ISSUE THREAD

**Issue by aaronkaplan** [cybergreen-net/stats-new#35]
When clicking on a country, there is no rank shown in the first small table

**Comment by rgrp** [comment]
@aaronkaplan we understood we should drop rank for this iteration (this was partly when discussion of new metrics). Shall we leave for now and re-add once we are clear how we want it to work. (Overall I am not sure how valuable doing ranking per week is as there may be a lot of fluctuation ...)

**Comment by aaronkaplan** [comment]
okay, agreed. closing.

**Comment by rufuspollock** [comment]
INVALID. Out of date.

**Comment by aaronkaplan** [comment]
keep it open in *order to not forget*.

**Comment by zelima** [comment]
DUPLICATE we can track this here https://github.com/cybergreen-net/stats-new/issues/259
