### ISSUE TITLE
Data in country table shows cumulative totals not most recent week causing confusion

### ISSUE THREAD

**Issue by aaronkaplan** [cybergreen-net/stats-new#36]
when going to /place/columbia (as an example) you will see that 
  1. the count in the first small table is very high (q: is that the total overall? if so, that's wrong).
  2. the numbers in the table below (ASN table) are very high (again, is that the total number over all time for that ASN?). However, when clicking on the ASN number and going to the detail page "asn/{integer}/" you will find quite regular and reasonable numbers.

Example: http://cybergreen-stats.herokuapp.com/place/colombia

ASN table says:
``` 3816         	4135106	133858	234380	3026663 ```
However when clicking on 3816 (http://cybergreen-stats.herokuapp.com/place/colombia/asn/3816/) you will find only 

420k open DNS servers. Not 4.1 million !

Something is still very very wrong here.

**Comment by zelima** [comment]
All the scores on website should be computed for latest given period (week) and should not be averaged fro totals. If there is no data for given risk for latest week, table show "N/A" for that risk.
