### ISSUE TITLE
download file name missing .CSV extension

### ISSUE THREAD

**Issue by aaronkaplan** [cybergreen-net/stats-new#37]
When you go to the download page and click on  "Full risk data" for CSV files, you will get a file called "country000". But it needs to be with a .csv extension in order to load it properly in a spreadsheet program.

Minor issue:
Different issue for the JSON data: it is displayed inline in the browser. The webserver needs to set the MIME type properly so that it gets downloaded.

**Comment by zelima** [comment]
@aaronkaplan We have risen issue to fix extensions here https://github.com/cybergreen-net/aggregator/issues/4

**Comment by rgrp** [comment]
DUPLICATE.
