### ISSUE TITLE
country page - data collected data/week

### ISSUE THREAD

**Issue by YurieIto** [cybergreen-net/stats-new#40]
country page - http://cybergreen-stats.herokuapp.com/country/

I am missing the time of the data collected.

**Comment by zelima** [comment]
Does this assume adding reference week right after Place overview? 
Eg: Place overview: 2016-08-15

**Comment by aaronkaplan** [comment]
> On 30 Sep 2016, at 10:13, Irakli Mchedlishvili <notifications@github.com> wrote:
> 
> Does this assume adding reference week right after Place overview?
> Eg: Place overview: 2016-08-15
> 

yes!
