### ISSUE TITLE
Remove score column on /risk/ page and any subpages

### ISSUE THREAD

**Issue by rgrp** [cybergreen-net/stats-new#41]
Noticed one regression vs stats v1 to fix tomorrow which there is "score" on risk page http://cybergreen-stats.herokuapp.com/risk/ - we should just delete that column - it should not be there ...

**Comment by zelima** [comment]
@rgrp Does this mean we should remove scores and ranks from /risk{id} page as well? eg http://cybergreen-stats.herokuapp.com/risk/opendns/

**Comment by rgrp** [comment]
@zelima what do we have on stats.cybergreen.net - follow what is there ...

**Comment by zelima** [comment]
This is fixed
