### ISSUE TITLE
regression: text in countries page is missing

### ISSUE THREAD

**Issue by aaronkaplan** [cybergreen-net/stats-new#42]
Please copy over the text from the old stats/ page to the places ("countries") page.
Please replace the line describing spam with:
``number of open recursive SNMP devices (opensnmp)``

**Comment by zelima** [comment]
@aaronkaplan This should be fixed, please confirm

**Comment by aaronkaplan** [comment]
"Open recursive" only works for DNS. 
SNMP is a different protocol. It make more sense to say "open SNMP". 

---
Mobile

**Comment by aaronkaplan** [comment]
PS: and i know I wrote b*s before myself :). 

I should not try to answer questions when actually busy with other things. Sorry. 

Anyway, "open recursive" makes only sense for DNS. All others it's "open". 

Sorry. 

---
Mobile
