### ISSUE TITLE
s/place/country/g

### ISSUE THREAD

**Issue by aaronkaplan** [cybergreen-net/stats-new#46]
As mentioned in #27 , please be consistent with replacing the word "Place" by "Country".
It was simply checkmarked as done, but actually it is *not* done consistently.

**Comment by zelima** [comment]
@aaronkaplan Can you give example link, where do we meet place instead of country again?

**Comment by aaronkaplan** [comment]
looks much better. Will test in more detail. But the occurrences that I saw before seem to be gone now! Thanks! Maybe I saw an older version online , when in fact it was already fixed in the code (?)

**Comment by aaronkaplan** [comment]
Found one!

![image](https://cloud.githubusercontent.com/assets/750019/19032613/1154f55a-895b-11e6-930f-2c3a2e20c031.png)

**Comment by zelima** [comment]
This one is fixed, any others? 
Leaving open for a while..

**Comment by aaronkaplan** [comment]
Yes!
API page: 
http://cybergreen-stats.herokuapp.com/download/

Ctrl-F "place". The API still uses the old name.

**Comment by aaronkaplan** [comment]
looks ok except for one item in the API documentation page. Search for "place". You'll see it there.

**Comment by aaronkaplan** [comment]
Same as #49
