### ISSUE TITLE
(minor thing - later): footer looks a bit weird

### ISSUE THREAD

**Issue by aaronkaplan** [cybergreen-net/stats-new#48]
Please improve the layout of the footer.

Currently it looks a bit messed up:

![image](https://cloud.githubusercontent.com/assets/750019/19009819/060f23d0-8778-11e6-822d-7b23312b9120.png)

**Comment by zelima** [comment]
@aaronkaplan Can I have more details here (What to add or remove). Right now it looks exactly like previous one http://stats.cybergreen.net/

**Comment by rgrp** [comment]
WONTFIX / INVALID. Unclear what is not working here so closing for now. Feel free to reopen if more clarity on what the task is.
