### ISSUE TITLE
(minor issue). Inconsistency: filter out "n/a" countries in country table

### ISSUE THREAD

**Issue by aaronkaplan** [cybergreen-net/stats-new#51]
in /country/, we say 
'Where there was no data, a "n/a" is shown. Countries with two or more "n/a" colums were filtered out.'
However, that's not the case when you look at the table. Please either remove the sentence ' Countries with two or more "n/a" colums were filtered out.' or re-implement that feature 
(after all, it was part of BETA-1).

**Comment by zelima** [comment]
@aaronkaplan which one is preferable? remove or re-implement?

**Comment by aaronkaplan** [comment]
I'd say re-implement in order to have relevant entries.
