### ISSUE TITLE
All the small UX bugs for Sep 2016 release

### ISSUE THREAD

**Issue by rgrp** [cybergreen-net/stats-new#6]
Please add UX bugs here rather than individual issues. We will address these in bulk post 26th.

* [x] HTML title looks to be empty on many pages
* [x] Small map shows drop-down menus next to each other, not on top of each other, preventing crowding out of map
* [x] Small map drop-down menus should be side-by-side (currently on top of each other, this is messy)
* [x] Front page map displays openntp by default, but there is no dropdown to look at anything else
* [x] Scores should be color coded
* [x] Search boxes above tables are not working
* [x] Main map: cannot click through on countries. No pop-up with link appears.
* [x] /asn/ page: s/Read more/Details/g

Secondary:
* [x] There is no explanatory text on /place (should there be?) -> yes, small one. 
* [x] Footer of site is untidy. Is it missing a logo or something?
* [x] /risk/ page says "Overview of Risks 2016"; this could be tidier eg "Overview of Risks: 2016" or "Overview of Risks (2016)"
* [x] Taller map (less squeezed vertically). See #30 
* [ ] **add yours here**

**Comment by Fak3** [comment]
On the issue with clickable countries on map: is there any detailed description? 
Does it apply the home page only, or other pages?
Should the popup link appear on hover or on click?
Is the popup needed at all, or we can just click the country to go to its page?

**Comment by aaronkaplan** [comment]
* @Fak3: basically this worked in beta-1 ( @rgrp do we still have that online somewhere to compare?) . See the code in stats-old/
* The clickable map should work on all pages IMHO
* on click
* popup is neat
