### ISSUE TITLE
bug: path wrong in country/$country/openntp

### ISSUE THREAD

**Issue by aaronkaplan** [cybergreen-net/stats-new#61]
Try going to country -> Iran -> click on openntp.

Result:
Cannot GET /country//openntp/

URL: http://cybergreen-stats.herokuapp.com/country//openntp/

Note the two "//". Probably something was forgotten when creating the URL path.

**Comment by zelima** [comment]
@aaronkaplan As there is no data for that country-risk couple on that week, there's no page to redirect. I'm making so that if this is the case, there will no link at all

**Comment by aaronkaplan** [comment]
works now. closing.
