### ISSUE TITLE
[OK] regression: API page does not describe output data format

### ISSUE THREAD

**Issue by aaronkaplan** [cybergreen-net/stats-new#63]
In [beta-1](http://stats.cybergreen.net/download/) we had a text describing the output format:

```
Aggregated data format
We currently provide full data dumps of our aggregated data sets. The CSV format is:

risk,place (country),year,count,score,rank

In addition to the above CSV format, we also provide a JSON download.
```

Please adapt the text to describe the current download.
Also a fix to the new download (CSV) full risk data:

 - the risk column is now a risk id. But we need the actual text ("opendns" etc). To be compatible with the old format.
 - might have to put the reference data (risk table (risk_id , risk_name)) into redshift

Please compare the previous download files with the current ones. You will see the difference.

**Comment by rgrp** [comment]
I think this is sensible however the issue incorporates both a tidy up and some new stuff (e.g. putting in risk table). I would suggest this is deferred until we are clear what columns we have going forward and that can happen as part of clarity around risk.

Generally, I would prefer to start having data descriptions driven off a datapackage.json to avoid this page getting out of sync, especially as columns change.

Summary: WONTFIX for now and we return to this in a few weeks.

**Comment by aaronkaplan** [comment]
The point here is that the stats group already needs the corrected data now.

**Comment by rgrp** [comment]
@aaronkaplan can we now close this? I know there is an issue about risk ids but this is something we need to resolve systematically and the info that was there in v1 is now up.

**Comment by rgrp** [comment]
WONTFIX / DUPLICATE #82. I've merged what i understand as the actionable stuff into #82 - please comment there.
