### ISSUE TITLE
[OK] Serious bug: API security

### ISSUE THREAD

**Issue by aaronkaplan** [cybergreen-net/stats-new#65]
This is an issue which I won't document publicly but only privately.
A friendly beta- tester team discovered a security issue with the API. This will be communicated privately and be fixed. However, this issue is a reminder and check mark if it's solved.

**Comment by aaronkaplan** [comment]
will be done. @zelima will push the commit and @aaronkaplan will test

**Comment by zelima** [comment]
This is fixed

**Comment by aaronkaplan** [comment]
> On 13 Oct 2016, at 16:24, Irakli Mchedlishvili <notifications@github.com> wrote:
> 
> Closed #65.
> 

Will re-test.
