### ISSUE TITLE
invalid countries create an application error (404 page missing)

### ISSUE THREAD

**Issue by aaronkaplan** [cybergreen-net/stats-new#66]
Try: http://cybergreen-stats.herokuapp.com/country/foobar

-> Application error.

Solution: please check the input from the URL against a _fixed_ list of expected inputs (i.e. a list of countries) on the server's side. Check case insensitively please.

**Comment by aaronkaplan** [comment]
how about making a 404 error?

**Comment by zelima** [comment]
@aaronkaplan Do we have 404 page?

**Comment by zelima** [comment]
Closing as `Application error` is not risen any more
new issue for 404 template https://github.com/cybergreen-net/stats-new/issues/90
