### ISSUE TITLE
[OK] application error with URL path

### ISSUE THREAD

**Issue by aaronkaplan** [cybergreen-net/stats-new#68]
When going to http://cybergreen-stats.herokuapp.com/country/austria/asn/35492/ you get a valid page.

Go to http://cybergreen-stats.herokuapp.com/country/austria/asn/ and we get an application error. This should not happen.

**Comment by zelima** [comment]
@aaronkaplan where should http://cybergreen-stats.herokuapp.com/country/austria/asn/ redirect?

**Comment by aaronkaplan** [comment]
> On 05 Oct 2016, at 17:19, Irakli Mchedlishvili <notifications@github.com> wrote:
> 
> @aaronkaplan where should http://cybergreen-stats.herokuapp.com/country/austria/asn/ redirect?
> 

It should result in a 404 error if it does not exist. I.e. "dear user, this page does not exist. Go look elsewhere".

It should not show an application error.

**Comment by rgrp** [comment]
@zelima i think this should redirect back to the country page.
