### ISSUE TITLE
treemap improvements

### ISSUE THREAD

**Issue by aaronkaplan** [cybergreen-net/stats-new#69]
@chorsley will provide a list of ASN to AS name mappings in the /refernence_data repository.

Please be so kind and use that table to include the AS name in the treemap.

The treemap shall:
- [ ] display the AS name when possible
- [ ] fetch AS infos from stat.ripe.net (see the API documentation there)
- [ ] _keep this here and add your own items to this list_

**Comment by zelima** [comment]
moved to #98
