### ISSUE TITLE
Basic API

### ISSUE THREAD

**Issue by rgrp** [cybergreen-net/stats-new#7]
Implement API spec listed here:

https://github.com/cybergreen-net/pm/issues/21

**Test first!**

Priority order:

* [x] `/api/v1/count_by_country`
* [x] Reference data ... - do not limit these ones - get everything ... 
 * [x] `/api/v1/risk`
 * [x] `/api/v1/country` - list of countries - the country reference dataset
 * [x] `/api/v1/asn` - list of asn
* [x] `/api/v1/count`
  * [x] ?country

### Backwards compatibility

**Not needed anymore!**

* [ ] <del>`/api/entries.json` -> redirect to `/api/v1/count_by_country?limit=2000`</de>
* [ ] <del>`/api/places.json` -> redirect to `/api/v1/country`</del>

What we have currently ...
```
[
{"risk": "opendns", "place": "ad", "year": "2016", "count": "30", "score": "25.77", "rank": "181"},
{"risk": "opendns", "place": "ae", "year": "2016", "count": "4280", "score": "63.35", "rank": "62"},
{"risk": "opendns", "place": "af", "year": "2016", "count": "890", "score": "51.45", "rank": "101"}, 
```

* place -> country
* year -> date

See #12 for changes to viz code

### Later

* [ ] `/api/v1/count`
  * [ ] ?asn
  * [ ] ?start and end
* [ ] `/api/v1/country/{id}.`
* [ ] `/api/v1/asn/{id}`
* [ ] Have `/api/count, /api/country/, /api/asn` redirect to `/api/v1/...`

**Comment by zelima** [comment]
[fixed: remaining items are in https://github.com/cybergreen-net/stats-new/issues/20
