### ISSUE TITLE
regression: ASN table in country/$country gone

### ISSUE THREAD

**Issue by aaronkaplan** [cybergreen-net/stats-new#70]
Seems our ASN table disappeared?

![image](https://cloud.githubusercontent.com/assets/750019/19150955/2a522368-8bca-11e6-8c66-4968600fb482.png)

**Comment by zelima** [comment]
We are reloading RDS with up to date data. This will be fixed automatically when it's done.

**Comment by aaronkaplan** [comment]
> On 06 Oct 2016, at 13:40, Irakli Mchedlishvili <notifications@github.com> wrote:
> 
> We are reloading RDS with up to date data. This will be fixed automatically when it's done.

okay, understood.
Thx!
