### ISSUE TITLE
API date inclusiveness

### ISSUE THREAD

**Issue by chorsley** [cybergreen-net/stats-new#74]
Knowing there's data available on 2016-08-08, if I view `/api/v1/count?limit=5&start=2016-08-08&end=2016-08-15`, I get 

`[]`

Likewise, if I view `/api/v1/count?limit=5&start=2016-08-01&end=2016-08-08`, I also get:

`[]`

If I view `/api/v1/count?limit=5&start=2016-08-07&end=2016-08-15`, I (as expected) get:

```
    {
        "asn": "6752",
        "count": "54",
        "country": "AD",
        "date": "2016-08-08",
        "period_type": "monthly",
        "risk": 2
    },
    ...
```

Is it correct to say data is are exclusive of the date limits themselves? As an API user, I'd expect data for these dates is included in the results.

**Comment by aaronkaplan** [comment]
> On 07 Oct 2016, at 07:53, Chris Horsley <notifications@github.com> wrote:
> 
> Knowing there's data available on 2016-08-08, if I view /api/v1/count?limit=5&start=2016-08-08&end=2016-08-15, I get
> 
> []
> 
> Likewise, if I view /api/v1/count?limit=5&start=2016-08-01&end=2016-08-08, I also get:
> 
> []
> 
> If I view /api/v1/count?limit=5&start=2016-08-07&end=2016-08-15, I (as expected) get:
> 
>     {
>         "asn": "6752",
>         "count": "54",
>         "country": "AD",
>         "date": "2016-08-08",
>         "period_type": "monthly",
>         "risk": 2
>     },
>     ...
> 
> Is it correct to say data is are exclusive of the date limits themselves? As an API user, I'd expect data for these dates is included in the results.
> 

Maybe it's a WHERE start > foo, when it should be in fact WHERE start >= foo ?

**Comment by zelima** [comment]
@chorsley @aaronkaplan should end date be inclusive as well?

**Comment by chorsley** [comment]
@zelima Yes, I (as an API user) would expect start and end date to be inclusive. For example, to get all October data, I'd specify 2016-10-01 start and 2016-10-31 end.
