### ISSUE TITLE
API count_by_country date ranges

### ISSUE THREAD

**Issue by chorsley** [cybergreen-net/stats-new#75]
It currently appears that an API query like `/api/v1/count_by_country?date=2016-08-08` returns data exactly on that date. It would be very handy for analysis purposes if a date range could be specified here. Finding the exact date a risk's data is available on is a bit of a brute force effort at the moment.

**Comment by chorsley** [comment]
Just to add to that - leaving out date returns all records I see. If that's intended behaviour, we might mention in API doco that date is optional.

**Comment by rgrp** [comment]
INVALID / FIXED. This is minor and i've made a note of it in #82

**Comment by rgrp** [comment]
Note a separate issue would be actual date range queries ...
