### ISSUE TITLE
Enabled s3 bucket listing on bits.cybergreen.net

### ISSUE THREAD

**Issue by rgrp** [cybergreen-net/stats-new#78]
[2]
https://github.com/rgrp/s3-bucket-listing

This will make the bits repo look like a nice filesystem that you can browse.

**Comment by zelima** [comment]
Bucket listing is available http://bits.cybergreen.net.s3-website-eu-west-1.amazonaws.com/

I guess, next step would be to create a CNAME record to map bits.cybergreen.net to http://bits.cybergreen.net.s3-website-eu-west-1.amazonaws.com/

**Comment by rgrp** [comment]
@zelima as per chat you need to do more analysis of what is not working and what you think the proposed fix is. Why would that CNAME make a difference?

**Comment by zelima** [comment]
@rgrp My guess here was that if bucket listing works on http://bits.cybergreen.net.s3-website-eu-west-1.amazonaws.com/ endpoint and not for bits.cybergreen.net I assumed they somehow needed to be mapped. (In my thoughts creation of CNAME record would do this).
IGNORING that. I dove in AWS [website hosting custom domain walkthrough docs](https://docs.aws.amazon.com/AmazonS3/latest/dev/website-hosting-custom-domain-walkthrough.html) further and got to this steps:
according to docs:
- > "You must use Amazon Route 53 if you want to serve content from your root domain, such as example.com"
- > "Before you switch to Amazon Route 53 as your DNS provider, you must transfer any remaining DNS records from your current DNS provider, including MX records, CNAME records, and A records, to Amazon Route 53"
- > "To switch to Amazon Route 53 as your DNS provider, you must go to your current DNS provider and update the name server (NS) record to use the name servers in your delegation set in Amazon Route 53."
- > "When the transfer to Amazon Route 53 is complete, there are tools that you can use to verify the name server for your domain has indeed changed."

So as steps to be done I would list:
- Create a Hosted Zone for Domain
- Transfer anything remaining DNS records (if there is any)
- switch to Amazon Route 53 as DNS provider

**Comment by rgrp** [comment]
@zelima i really don't think this is a DNS issue but i'm not certain. http://data.openspending.org/ seems to work fine right ... (how is this site different). Have you done any analysis in the chrome inspector of what is going wrong ...

**Comment by zelima** [comment]
@rgrp Will go through https://github.com/rgrp/s3-bucket-listing docs more carefully once again. Maybe missing something.

**Comment by zelima** [comment]
@aaronkaplan found the problem here: currently CNAME `bits.cybergreen.net` Is mapped to `bits-cybergreen-net.s3.amazonaws.com`.
 
To fix this issue we need it to be mapped to the website mode: `bits.cybergreen.net.s3-website-eu-west-1.amazonaws.com`.

Could you please contact DNS provider and ask to make that change. And we can close this one.

**Comment by zelima** [comment]
Fixed - S3 bucket listing enabled http://bits.cybergreen.net/
