### ISSUE TITLE
[api] Download CSV from the API (with headers)

### ISSUE THREAD

**Issue by ManelMedina** [cybergreen-net/stats-new#79]
I think that a "traditional" csv file, with a headers row would be easier to integrate into any processing system
I used the command of the API to download some data,  I got one line with entries in {} per week.date, threat, country and ASN in the format  [{<tag>:<value>,...,<tag>:<value>}, ... ,{...}]
To use that in excel or R program it is necessary to remove all formatting info, whilst csv would be authomatic.
 <value>,<value>,<value> <CR><LF>...

**Comment by zelima** [comment]
FIXED see example: https://cybergreen-staging.herokuapp.com/api/v1/count_by_country?country=gb&format=csv&filename=my-awsome-statistics
