### ISSUE TITLE
map : captures the context, confusing

### ISSUE THREAD

**Issue by aaronkaplan** [cybergreen-net/stats-new#80]
Main page -> map. Once in there it might be confusing since the map captures the scrolling

**Comment by zelima** [comment]
@aaronkaplan I'd like to have more details about this one - I don't really get it.

**Comment by rgrp** [comment]
WONTFIX. This is pretty hard to fix IMO and I'm not sure it is a big UX issue and may go away when we have less text and more map on the front page. Feel free to reopen in future if this is persistent problem and is still there after we rework the page.
