### ISSUE TITLE
[super] Time period chooser for all visualizations (maps, time series etc)

### ISSUE THREAD

**Issue by rufuspollock** [cybergreen-net/stats-new#84]
_This is a big issue and in need of discussion. Stubbing for now as a placeholder_.

Note this maybe should expand to having a date version of each page. This would imply changes to information architecture.

**Comment by zelima** [comment]
@rufuspollock as we are having time series graphs on almost all pages, I assume this is not relevant any more.

**Comment by rufuspollock** [comment]
INVALID / WONTFIX.
