### ISSUE TITLE
(feedback from stats-WG): rename "open DNS" to "open recursive DNS"

### ISSUE THREAD

**Issue by aaronkaplan** [cybergreen-net/stats-new#85]
Feedback from the stats-WG: 
   "open DNS " is the name of a product / company. We should call the thing by its proper name: "open recursive DNS".
Please sift through all the files (grep -R) and the DBs and change it.
Thanks.

**Comment by aaronkaplan** [comment]
more stuff coming... did not get to write it down yet, sorry

**Comment by rgrp** [comment]
@aaronkaplan before we change can we get this properly clarified. E.g. what would be the user friendly id for urls? e.g. open-recursive-dns, open-dns etc. Also we first change this in reference data then it will flow through to the frontend.

**Comment by aaronkaplan** [comment]
"openrecursivedns/" or "open-recursive-dns" ... does not matter. 
As long as we are consistent everywhere.

**Comment by zelima** [comment]
@aaronkaplan Any updates on this, or we can close?

**Comment by zelima** [comment]
@aaronkaplan any updates on this, or we can close? 
> more stuff coming... did not get to write it down yet, sorry

**Comment by zelima** [comment]
FIXED. let's reopen when/if needed

**Comment by rufuspollock** [comment]
@zelima is this FIXED or WONTFIX?

**Comment by zelima** [comment]
@rufuspollock FIXED Eg: https://cybergreen-staging.herokuapp.com/risk/open-recursive-dns
