### ISSUE TITLE
404 template

### ISSUE THREAD

**Issue by zelima** [cybergreen-net/stats-new#90]
Split from https://github.com/cybergreen-net/stats-new/issues/66 

Need template text for 404 pages

**Comment by zelima** [comment]
@rufuspollock will be using same layout as for http://www.cybergreen.net/unknown

**Comment by rufuspollock** [comment]
@zelima i would not use the www site as not very good. Just use our standard template for site and put a nice big 404 in middle and invite people to return to home page or report issue with contact form (if we have one on the main site).

**Comment by zelima** [comment]
FIXED. see http://cybergreen-staging.herokuapp.com/notapage

**Comment by rufuspollock** [comment]
@zelima have to say i did not much like the www one and ux was poor ;-) (e.g. no instructions on where to go). However, a more beautiful 404 is something we can look at later!
