### ISSUE TITLE
Query options for count API (slice by dimensions)

### ISSUE THREAD

**Issue by zelima** [cybergreen-net/stats-new#91]
separated from #83 

## Query options for count

- [x] Limit: Query results should be default limited to 20 items. (Use LIMIT In SQL). Can be changed using `?limit=`. Max value for limit should be 500.
- [x] Sort: sort in time order backwards (so latest data first by default) and sort by country id alphabetically
  - [x]  **So by default data from `/count` and `/count_by_country` should give _latest_ data**
- [x] Time queries: ?start=yyyy-mm-dd&end=yyyy-mm-dd
- [x] start or end can be optional and in which case after or before queries
- [x] Country query: ?country={id}
- [x] ASN query: ?asn={id}

**UPDATE**
- [ ] Is this list missing risk query? - `?risk={id}`

**Comment by zelima** [comment]
Will add query the risk-id parameter if we need it and we can close this one

**Comment by rgrp** [comment]
@zelima would risk id be number e.g. 1 or text e.g. openntp - i suggest we try and support both.

**Comment by zelima** [comment]
Fixed - Risk query added
