### ISSUE TITLE
Count label cut off on right-hand points of ASN timeseries

### ISSUE THREAD

**Issue by chorsley** [cybergreen-net/stats-new#93]
Mousing over points on the right side of an ASN time series graphs pops up a label, but the count itself is cropped out:

![image](https://cloud.githubusercontent.com/assets/383615/19967186/8d625316-a212-11e6-9c87-a24a17c9c826.png)

**Comment by aaronkaplan** [comment]
reminds me: the mouse over is not very tolerant on the graph.

**Comment by rgrp** [comment]
May try to look at this but may not be very easy so may be post beta-3.

**Comment by rufuspollock** [comment]
There is a "proper" fix - https://github.com/rufuspollock/line-charts/issues/40

Alternatively - just add space on the right of the chart.

**Comment by zelima** [comment]
Moving to backlog for now as we might start using other library for graphs and charts

**Comment by zelima** [comment]
FIXED / INVALID this was relevant when we were using other library for rendering graphs. 
As we switched to [Plotly](https://plot.ly/) this is not actual any more
