### ISSUE TITLE
Mouseover region for ASN timeseries graph

### ISSUE THREAD

**Issue by chorsley** [cybergreen-net/stats-new#94]
When mousing over points on the ASN timeseries graph, it's often the case that the expanded red region is different to the region which triggers the "Count" label to popup. Suggestion: both trigger regions be made the same size so it's more intuitive where to place the mouse cursor to see the count label.

**Comment by zelima** [comment]
Fixed. red circles and popup values should match

**Comment by chorsley** [comment]
Much better now, thanks!

One more issue - it seems the label and highlight doesn't trigger when the cursor is right in the middle of a point.  When you enter the edge of a point with your cursor it highlights and the label displays, but as you pass through the middle, it disappears, and then reappears as you move through.

**Comment by zelima** [comment]
@chorsley I'll see what can I do, hope this is not bug of graph library.

**Comment by chorsley** [comment]
@zelima Perfect, thanks!
