### ISSUE TITLE
Support for "week of year" queries and values

### ISSUE THREAD

**Issue by chorsley** [cybergreen-net/stats-new#95]
Currently, all aggregate risk data is searchable and indexed by date (yyyy-mm-dd). However, the base time unit we are analysing data against is really week of the year. If a scan occurs for risk 1 on 2016-11-01, and risk 2 on 2016-11-03, there should be a simple method to establish these occurred within the same week.

I suggest using a "week of year" value (e.g. https://en.wikipedia.org/wiki/ISO_week_date), which is both included in results and is also a searchable parameter. That way, I can simply search for week 45 2016 of both risk 1 and risk 2, and know that they correspond to one another for scoring purposes. We should still include the actual scan date as this may be important for analysis.

This would also be very useful in visualisations and reports when we want to display different risks together, and show how they compare week by week without having to somehow realign dates or do fiddly date calculations on the fly.

**Comment by rgrp** [comment]
@chorsley good point. Whilst we are currently using yyyy-mm-dd really I note the data is already aggregated at the week not the day level. Thus, these dates correspond to the start of weeks and we don't have dates other than the start of weeks.

In terms of how we put this in the UI that is good question.

**Comment by chorsley** [comment]
The issue we have here is that the scans occur on different days that aren't always the start of the week. For example, last week's scans were on:

openntp: 2016-11-18
openssdp: 2016-11-19 
opendns: 2016-11-20
opensnmp: 2016-11-22

This is a particular quirk of the open* data sets we initially get, however. 

A second issue: later, we'd expect to receive new data feeds that span multiple days because of the length of the scan process, or because it's continuously collected over the course of a week. We'll need some way to tie this to a particular week so the data is comparable between risk types.

So, going to week-of-year as a primary means of date selection would let us easily compare the four above for a start, without the API user needing to do their own complex date calculations requiring knowledge of the peculiarities of each scan data's schedule.

This would likely need to be combined with the idea of fixing all data in a single data batch to a particular week (e.g. of first record in batch), in the case of the scan process bridging across multiple weeks of the year.

**Comment by rgrp** [comment]
@chorsley i think this info would be better in https://github.com/cybergreen-net/pm/issues/70 - and I have copied across.

I think we reserve this item for actually implementing week of year queries in the API e.g. ?2016W23 or something.

**Comment by rgrp** [comment]
Moving to Backlog as this depends really on the DW refactor which will take us past Beta-3.

**Comment by rufuspollock** [comment]
WONTFIX. Don't plan to fix this atm and not sure it is needed.
