### ISSUE TITLE
Selectable date display for risk pages

### ISSUE THREAD

**Issue by chorsley** [cybergreen-net/stats-new#97]
Currently, a risk page (e.g. http://cybergreen-stats.herokuapp.com/risk/opensnmp/) can only display data for the latest week received. If we have a week missing for some reason, it would be good to go back to the last available data, or we may want to see the state of a risk at a particular point in time.

Much like we can with the API or the map, it would be great if we could show a dropdown of all the dates with data we have available, and then pass this date parameter to the risk page to show the corresponding data.

**Comment by rufuspollock** [comment]
WONTFIX / INVALID. With new setup planned for time series graph this won't be valid.
