### ISSUE TITLE
[super] Treemap improvements full

### ISSUE THREAD

**Issue by zelima** [cybergreen-net/stats-new#98]
This merges items from #22 #69 #81 into one for better tracking. Please add here anything related to treemap 

- [ ] Colour-coding according to comparison with historical averages
- [ ] Hovering over a country / ASN shows the trend graph or other stats
- [ ] Filter for country name / ASN by search field (where?)
- [ ] Hover over ASN displays the AS name and other info from stat.ripe.net (see the API documentation there) - #101
- [ ] 80/20 rule 
- [ ] We may consider grouping all ASNs below a % threshold, into an "other" box. (under discussion)
- [ ] Fancier for later consideration: feature allowing zooming, which doesn't render all boxes at high level, but may do after zooming to lower detail level. (under discussion)
- [ ] _keep this here and add your own items to this list_

**Comment by aaronkaplan** [comment]
Irakli, please sync on this with @chorsley . He made a demo of a treemap. You might want to re-use that or at least look at it - in order to save time and effort and work.

**Comment by zelima** [comment]
@aaronkaplan yes I've seen that.
@chorsley cc
- treemap "gathers" asns on continent level, so I'm little bit confused how that one is refereed to the one we need (since our treemap shows asns of exact country). Little bit more details would be useful
- **Filter for country name / ASN by search field** - Is this for Treemap at all, or for table? cause what should it result?
- **80/20 rule** - is there some algorithm for this or we just need to show **important** asns? And how it is determined _important_ and _not important_ ones? By some %? if yes how big would that % be?

**Comment by chorsley** [comment]
@zelima 

> That example treemap "gathers" asns on continent level, so I'm little bit confused how that one is referred to the one we need (since our treemap shows asns of exact country). Little bit more details would be useful

I would use three different display levels for the treemap: continent, then countries in the continent, then ASNs in the country.  As well as navigating links on the treemap get the next level down, it would also be useful to have direct URLs into any level (e.g. can link straight to ASNs in Brazil).

A zoomable treemap (e.g. http://bl.ocks.org/ganeshv/6a8e9ada3ab7f2d88022) is also very useful to help users keep the context how data fits into the whole.

> Filter for country name / ASN by search field - Is this for Treemap at all, or for table? cause what should it result, single box?

Yes, it should highlight the particular treemap box (or its parent) holding matching items. 

This would allow searching for a country or an ASN. For example, if you were at the continent level and entered ASN 123 (assuming 123 is in the US), it would highlight the box for North America, then after the user clicks on North America, highlight the United States, then clicking on the United States, shows a highlight around the exact ASN in question.

One of the first things that people will want to do is find their own country or ASN quickly, and if there are hundreds in a particular country, we want to make finding a single one as simple as possible.

> 80/20 rule - is there some algorithm for this or we just need to show important asns? And how it is determined important and not important ones? By some %? if yes how big would that % be?

I would do something along the lines of grouping the last 20% of treemap boxes into a single "others" box. Ideally, we can find a treemap library which already does this for us. This is really a hack to avoid the browser choking with thousands of boxes. If we find that the particular JS treemap library we use handles thousands of boxes okay, we can just hide labels for small boxes, and users may find these using the search, or by zooming.

One more feature that would be very useful. If we're looking at ASNs for a particular risk, it would be great to show the timeseries graph of the count over time when hovering over a box, e.g. https://d3plus.org/million_songs/tree_map_albums.html.

It would be well worth investigating the state of the art in JS treemap libraries, and seeing which already offer a majority of these features.

**Comment by zelima** [comment]
@chorsley 
- I understand the idea of different levels. Just, we are already on lowest (country) level, when displaying Treemap. It is to show ASNs for **exact** country E.g: http://cybergreen-stats.herokuapp.com/country/bosnia-and-herzegovina/ . Think having different levels would make more sense if we had treemap on the page where all countries are displayed http://cybergreen-stats.herokuapp.com/country . Are we talking about this?
- Got the idea of filtering.
- Reffering to 80/20 rule. When you say 20% of boxes: 
 - you mean 20% of them in any cases? Cause E.g if there are 10 ASNs with equal number of infections(E.g: 10). should "last" 2 be gathered in "other" box? Cause that would make "other" box be the biggest one. (With 20 infections in it)
 - Or maybe all the ASN's that have number of infections less then 20% of total sum of infections. Still not good choice, cause using same example, it would lead every single one gather in "other" box. As 100*0.2 > 10
 - Or maybe take the ones that have number of infection less then 20% of ASN with **Biggest** number of infection. on the same example it would leave every single them untouched. But if there was one ASN with count of 70 and other 9 with count of 3, this would result with 2 boxes - "other" and the biggest one.

**Comment by zelima** [comment]
WONTFIX this is mostly implemented in Source of Infection - AS bar charts epic #161. 

The main idea of having treemap was to know "worst" asn numbers in my country, we accomplished this by showing worst 5  AS numbers (+ rest) for each month (or any other time granularity) with a stacked bar chart, giving user a Idea of which AS to are mainly responsible for country's performance. 
For example see Right Half of screen : https://cybergreen-staging.herokuapp.com/country/united-kingdom
